<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class BiologySeeder extends Seeder
{
    public function run(): void
    {
        Question::truncate();

        $questions = [
            // ── Cell Biology ───────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2024,
                'question_text' => 'Which organelle is known as the powerhouse of the cell?',
                'options' => ['Mitochondrion', 'Ribosome', 'Nucleus', 'Vacuole'],
                'correct_answer' => 0,
                'explanation' => 'Mitochondria release energy through respiration and are called the powerhouse of the cell.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2023,
                'question_text' => 'The structure that controls the entry and exit of substances into the cell is the:',
                'options' => ['cell membrane', 'cell wall', 'cytoplasm', 'nucleolus'],
                'correct_answer' => 0,
                'explanation' => 'The cell membrane is selectively permeable and regulates movement of substances.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2022,
                'question_text' => 'Which structure is found in plant cells but not in animal cells?',
                'options' => ['Cell wall', 'Mitochondrion', 'Ribosome', 'Cytoplasm'],
                'correct_answer' => 0,
                'explanation' => 'Plant cells have a cellulose cell wall; animal cells do not.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2021,
                'question_text' => 'The site of protein synthesis in the cell is the:',
                'options' => ['Ribosome', 'Golgi apparatus', 'Lysosome', 'Vacuole'],
                'correct_answer' => 0,
                'explanation' => 'Ribosomes translate mRNA into proteins.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2020,
                'question_text' => 'Chromosomes are composed mainly of:',
                'options' => ['DNA and protein', 'RNA and lipid', 'Cellulose and starch', 'Protein only'],
                'correct_answer' => 0,
                'explanation' => 'Chromosomes are made of DNA wrapped around histone proteins.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2019,
                'question_text' => 'The movement of water molecules through a semi-permeable membrane from a dilute solution to a concentrated one is called:',
                'options' => ['Osmosis', 'Diffusion', 'Active transport', 'Transpiration'],
                'correct_answer' => 0,
                'explanation' => 'Osmosis is the movement of water across a semi-permeable membrane.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2018,
                'question_text' => 'The movement of particles from a region of higher concentration to a region of lower concentration is:',
                'options' => ['Diffusion', 'Osmosis', 'Plasmolysis', 'Phototropism'],
                'correct_answer' => 0,
                'explanation' => 'Diffusion is the net movement of particles down a concentration gradient.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2024,
                'question_text' => 'The structure that contains cell sap in a plant cell is the:',
                'options' => ['Vacuole', 'Nucleus', 'Mitochondrion', 'Centriole'],
                'correct_answer' => 0,
                'explanation' => 'The vacuole stores cell sap and helps maintain turgor pressure.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2023,
                'question_text' => 'The part of the cell that controls activities and contains genetic material is the:',
                'options' => ['Nucleus', 'Ribosome', 'Cell wall', 'Cytoplasm'],
                'correct_answer' => 0,
                'explanation' => 'The nucleus controls cell activities and houses chromosomes.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Cell Biology',
                'year' => 2022,
                'question_text' => 'Plasmolysis occurs when a plant cell is placed in a:',
                'options' => ['hypertonic solution', 'hypotonic solution', 'isotonic solution', 'distilled water'],
                'correct_answer' => 0,
                'explanation' => 'Water leaves the cell in a hypertonic solution, causing the cytoplasm to shrink away from the wall.',
                'difficulty' => 'medium',
            ],

            // ── Classification of Living Things ───────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2024,
                'question_text' => 'Which kingdom contains mostly unicellular prokaryotic organisms?',
                'options' => ['Monera', 'Plantae', 'Fungi', 'Animalia'],
                'correct_answer' => 0,
                'explanation' => 'Monera includes prokaryotic organisms such as bacteria.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2023,
                'question_text' => 'The scientific name of an organism consists of the:',
                'options' => ['genus and species', 'family and order', 'kingdom and phylum', 'class and order'],
                'correct_answer' => 0,
                'explanation' => 'Binomial nomenclature uses the genus name followed by the species name.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2022,
                'question_text' => 'Animals with a backbone are called:',
                'options' => ['Vertebrates', 'Invertebrates', 'Amphibians', 'Molluscs'],
                'correct_answer' => 0,
                'explanation' => 'Vertebrates are animals that possess a vertebral column.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2021,
                'question_text' => 'Which of the following is a mammalian feature?',
                'options' => ['Mammary glands', 'Gills', 'Feathers', 'Scales'],
                'correct_answer' => 0,
                'explanation' => 'Mammary glands are a defining feature of mammals.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2020,
                'question_text' => 'The body of an insect is divided into the:',
                'options' => ['head, thorax and abdomen', 'head and trunk', 'thorax and abdomen only', 'head, abdomen and tail'],
                'correct_answer' => 0,
                'explanation' => 'Insects have three body parts: head, thorax and abdomen.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2019,
                'question_text' => 'Which class does a frog belong to?',
                'options' => ['Amphibia', 'Reptilia', 'Pisces', 'Aves'],
                'correct_answer' => 0,
                'explanation' => 'Frogs are amphibians.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2018,
                'question_text' => 'The cell wall of fungi is made mainly of:',
                'options' => ['Chitin', 'Cellulose', 'Peptidoglycan', 'Starch'],
                'correct_answer' => 0,
                'explanation' => 'Fungal cell walls contain chitin.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2024,
                'question_text' => 'Which of the following is a characteristic of birds?',
                'options' => ['Feathers', 'Mammary glands', 'Wet skin', 'Gills'],
                'correct_answer' => 0,
                'explanation' => 'Feathers are unique to birds.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2022,
                'question_text' => 'A key characteristic of arthropods is the presence of:',
                'options' => ['jointed appendages', 'feathers', 'hair', 'milk glands'],
                'correct_answer' => 0,
                'explanation' => 'Arthropods have jointed appendages and an exoskeleton.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Classification',
                'year' => 2021,
                'question_text' => 'Which of the following is a unicellular organism?',
                'options' => ['Amoeba', 'Mango tree', 'Cat', 'Maize'],
                'correct_answer' => 0,
                'explanation' => 'Amoeba is a unicellular protozoan.',
                'difficulty' => 'easy',
            ],

            // ── Ecology ───────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2024,
                'question_text' => 'Organisms that make their own food using sunlight are called:',
                'options' => ['Autotrophs', 'Heterotrophs', 'Parasites', 'Saprophytes'],
                'correct_answer' => 0,
                'explanation' => 'Autotrophs produce their own food, usually by photosynthesis.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2023,
                'question_text' => 'A food chain always begins with a:',
                'options' => ['producer', 'decomposer', 'consumer', 'predator'],
                'correct_answer' => 0,
                'explanation' => 'Producers form the first trophic level in a food chain.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2022,
                'question_text' => 'A relationship in which both organisms benefit is:',
                'options' => ['Mutualism', 'Parasitism', 'Commensalism', 'Competition'],
                'correct_answer' => 0,
                'explanation' => 'Both organisms benefit in mutualism.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2021,
                'question_text' => 'The process by which nitrates are converted into nitrogen gas is:',
                'options' => ['Denitrification', 'Nitrification', 'Ammonification', 'Nitrogen fixation'],
                'correct_answer' => 0,
                'explanation' => 'Denitrification converts nitrates to atmospheric nitrogen.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2020,
                'question_text' => 'Which of the following is an abiotic factor?',
                'options' => ['Light', 'Grass', 'Frog', 'Bacteria'],
                'correct_answer' => 0,
                'explanation' => 'Abiotic factors are non-living, such as light, temperature and water.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2019,
                'question_text' => 'The place where an organism lives is its:',
                'options' => ['habitat', 'niche', 'population', 'community'],
                'correct_answer' => 0,
                'explanation' => 'Habitat is the natural home of an organism.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2018,
                'question_text' => 'The role of an organism in its environment is its:',
                'options' => ['niche', 'habitat', 'population', 'ecosystem'],
                'correct_answer' => 0,
                'explanation' => 'Niche describes an organism\'s role or function in an ecosystem.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2024,
                'question_text' => 'A group of organisms of the same species living in a particular area is a:',
                'options' => ['population', 'community', 'ecosystem', 'habitat'],
                'correct_answer' => 0,
                'explanation' => 'A population consists of members of the same species in an area.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2023,
                'question_text' => 'Which organisms break down dead organic matter?',
                'options' => ['Decomposers', 'Producers', 'Predators', 'Parasites'],
                'correct_answer' => 0,
                'explanation' => 'Decomposers recycle nutrients by breaking down dead organisms.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Ecology',
                'year' => 2022,
                'question_text' => 'The living component of an ecosystem is called the:',
                'options' => ['biotic component', 'abiotic component', 'lithosphere', 'hydrosphere'],
                'correct_answer' => 0,
                'explanation' => 'Biotic components are the living parts of the ecosystem.',
                'difficulty' => 'easy',
            ],

            // ── Genetics ──────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2024,
                'question_text' => 'The genetic makeup of an organism is its:',
                'options' => ['genotype', 'phenotype', 'allele', 'locus'],
                'correct_answer' => 0,
                'explanation' => 'Genotype refers to the genes an organism carries.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2023,
                'question_text' => 'The observable characteristics of an organism are called its:',
                'options' => ['phenotype', 'genotype', 'chromosome', 'allele'],
                'correct_answer' => 0,
                'explanation' => 'Phenotype is the visible expression of genes.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2022,
                'question_text' => 'An alternative form of a gene is called an:',
                'options' => ['allele', 'locus', 'chromatid', 'genome'],
                'correct_answer' => 0,
                'explanation' => 'Different forms of the same gene are called alleles.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2021,
                'question_text' => 'An individual with two identical alleles for a trait is:',
                'options' => ['homozygous', 'heterozygous', 'hybrid', 'mutant'],
                'correct_answer' => 0,
                'explanation' => 'Homozygous means the alleles are the same.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2020,
                'question_text' => 'An individual with two different alleles for a trait is:',
                'options' => ['heterozygous', 'homozygous', 'dominant', 'recessive'],
                'correct_answer' => 0,
                'explanation' => 'Heterozygous means having two different alleles.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2019,
                'question_text' => 'In a monohybrid cross between Tt and Tt, the phenotypic ratio is:',
                'options' => ['3:1', '1:1', '1:2:1', '9:3:3:1'],
                'correct_answer' => 0,
                'explanation' => 'A Tt x Tt cross gives 3 dominant to 1 recessive phenotype.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2018,
                'question_text' => 'Which of the following is a sex-linked trait?',
                'options' => ['Colour blindness', 'Height', 'Blood group', 'Skin colour'],
                'correct_answer' => 0,
                'explanation' => 'Colour blindness is commonly carried on the X chromosome.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2024,
                'question_text' => 'The genotype for blood group O is:',
                'options' => ['ii', 'IAIB', 'IAIA', 'IBIB'],
                'correct_answer' => 0,
                'explanation' => 'Blood group O is recessive and has genotype ii.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2023,
                'question_text' => 'A mutation involving a change in one nucleotide is a:',
                'options' => ['point mutation', 'chromosomal mutation', 'polyploidy', 'crossing over'],
                'correct_answer' => 0,
                'explanation' => 'A point mutation affects a single nucleotide base.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Genetics',
                'year' => 2022,
                'question_text' => 'Mendel\'s law of independent assortment states that:',
                'options' => ['genes for different traits are inherited independently', 'dominant genes always appear together', 'all traits are inherited from the father only', 'alleles never separate'],
                'correct_answer' => 0,
                'explanation' => 'Genes for different traits assort independently during gamete formation.',
                'difficulty' => 'medium',
            ],

            // ── Human Reproduction ────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2024,
                'question_text' => 'The male gamete is produced in the:',
                'options' => ['testis', 'ovary', 'uterus', 'cervix'],
                'correct_answer' => 0,
                'explanation' => 'Sperm cells are produced in the testes.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2023,
                'question_text' => 'The female gamete is produced in the:',
                'options' => ['ovary', 'testis', 'vas deferens', 'ureter'],
                'correct_answer' => 0,
                'explanation' => 'Ova are produced in the ovaries.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2022,
                'question_text' => 'Fertilization in humans usually occurs in the:',
                'options' => ['fallopian tube', 'uterus', 'vagina', 'cervix'],
                'correct_answer' => 0,
                'explanation' => 'The union of sperm and egg usually occurs in the oviduct (fallopian tube).',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2021,
                'question_text' => 'The organ where the foetus develops is the:',
                'options' => ['uterus', 'ovary', 'urethra', 'placenta'],
                'correct_answer' => 0,
                'explanation' => 'The uterus is the womb where foetal development occurs.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2020,
                'question_text' => 'The placenta is responsible for:',
                'options' => ['exchange of materials between mother and foetus', 'production of sperm', 'storage of urine', 'digestion of food'],
                'correct_answer' => 0,
                'explanation' => 'The placenta allows exchange of nutrients, gases and wastes between mother and foetus.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2019,
                'question_text' => 'Menstruation is the:',
                'options' => ['shedding of the uterine lining', 'release of sperm', 'fertilization of an ovum', 'growth of a baby'],
                'correct_answer' => 0,
                'explanation' => 'Menstruation is the periodic shedding of the endometrium.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2018,
                'question_text' => 'The prostate gland adds fluid to the:',
                'options' => ['semen', 'urine', 'bile', 'blood'],
                'correct_answer' => 0,
                'explanation' => 'The prostate gland contributes fluid that forms part of semen.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2023,
                'question_text' => 'Puberty in humans is mainly brought about by the action of:',
                'options' => ['sex hormones', 'digestive enzymes', 'antibodies', 'vitamins'],
                'correct_answer' => 0,
                'explanation' => 'Sex hormones trigger the physical and reproductive changes of puberty.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2022,
                'question_text' => 'A condom acts mainly as a:',
                'options' => ['barrier method of contraception', 'hormonal implant', 'sterilization method', 'fertility drug'],
                'correct_answer' => 0,
                'explanation' => 'A condom prevents sperm from entering the female reproductive tract.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Human Reproduction',
                'year' => 2021,
                'question_text' => 'The female sex hormone that prepares the uterus for pregnancy is:',
                'options' => ['progesterone', 'adrenaline', 'insulin', 'thyroxine'],
                'correct_answer' => 0,
                'explanation' => 'Progesterone maintains the uterine lining for possible implantation.',
                'difficulty' => 'medium',
            ],

            // ── Nutrition and Digestion ────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2024,
                'question_text' => 'The enzyme present in saliva is:',
                'options' => ['amylase', 'pepsin', 'lipase', 'trypsin'],
                'correct_answer' => 0,
                'explanation' => 'Salivary amylase begins the digestion of starch in the mouth.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2023,
                'question_text' => 'Digestion of food begins in the:',
                'options' => ['mouth', 'stomach', 'small intestine', 'colon'],
                'correct_answer' => 0,
                'explanation' => 'Mechanical and chemical digestion begin in the mouth.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2022,
                'question_text' => 'Bile helps in the digestion of fats by:',
                'options' => ['emulsification', 'hydrolysis', 'absorption', 'fermentation'],
                'correct_answer' => 0,
                'explanation' => 'Bile breaks large fat droplets into smaller droplets.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2021,
                'question_text' => 'The main site of absorption of digested food is the:',
                'options' => ['small intestine', 'oesophagus', 'stomach', 'liver'],
                'correct_answer' => 0,
                'explanation' => 'Villi in the small intestine absorb digested nutrients.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2020,
                'question_text' => 'Pepsin works best in the:',
                'options' => ['stomach', 'mouth', 'large intestine', 'pancreas'],
                'correct_answer' => 0,
                'explanation' => 'Pepsin is active in the acidic environment of the stomach.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2019,
                'question_text' => 'Proteins are mainly needed in the body for:',
                'options' => ['growth and repair', 'energy storage only', 'bone softening', 'water absorption only'],
                'correct_answer' => 0,
                'explanation' => 'Proteins are essential for growth and tissue repair.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2018,
                'question_text' => 'A deficiency of vitamin C causes:',
                'options' => ['scurvy', 'rickets', 'night blindness', 'anaemia'],
                'correct_answer' => 0,
                'explanation' => 'Vitamin C deficiency leads to scurvy.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2024,
                'question_text' => 'Roughage in the diet mainly helps to:',
                'options' => ['aid bowel movement', 'provide vitamins', 'build muscles', 'produce enzymes'],
                'correct_answer' => 0,
                'explanation' => 'Roughage adds bulk and helps peristalsis.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2023,
                'question_text' => 'The teeth used for cutting food are the:',
                'options' => ['incisors', 'molars', 'premolars', 'canines'],
                'correct_answer' => 0,
                'explanation' => 'Incisors are adapted for biting and cutting.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Nutrition',
                'year' => 2022,
                'question_text' => 'A balanced diet is one that contains nutrients:',
                'options' => ['in the right proportions', 'only in large amounts', 'only proteins and carbohydrates', 'without water'],
                'correct_answer' => 0,
                'explanation' => 'A balanced diet contains all nutrients in suitable amounts and proportions.',
                'difficulty' => 'easy',
            ],

            // ── Transport, Respiration, Excretion and Nervous System ──────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2024,
                'question_text' => 'Blood vessels that carry blood away from the heart are:',
                'options' => ['arteries', 'veins', 'capillaries', 'venules'],
                'correct_answer' => 0,
                'explanation' => 'Arteries carry blood away from the heart.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2023,
                'question_text' => 'Veins have valves to prevent:',
                'options' => ['backflow of blood', 'blood clotting', 'oxygen transport', 'cell division'],
                'correct_answer' => 0,
                'explanation' => 'Valves prevent blood from flowing backward in veins.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2022,
                'question_text' => 'The pigment that carries oxygen in red blood cells is:',
                'options' => ['haemoglobin', 'chlorophyll', 'melanin', 'carotene'],
                'correct_answer' => 0,
                'explanation' => 'Haemoglobin binds oxygen and transports it in the blood.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2021,
                'question_text' => 'The site of gaseous exchange in the lungs is the:',
                'options' => ['alveolus', 'trachea', 'bronchus', 'larynx'],
                'correct_answer' => 0,
                'explanation' => 'Alveoli are thin-walled air sacs where gas exchange occurs.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2020,
                'question_text' => 'The windpipe is also called the:',
                'options' => ['trachea', 'oesophagus', 'larynx', 'diaphragm'],
                'correct_answer' => 0,
                'explanation' => 'The trachea is the windpipe.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2019,
                'question_text' => 'Aerobic respiration produces:',
                'options' => ['carbon dioxide, water and energy', 'alcohol and carbon dioxide', 'lactic acid only', 'oxygen and glucose'],
                'correct_answer' => 0,
                'explanation' => 'Aerobic respiration breaks down glucose in the presence of oxygen to release energy.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2018,
                'question_text' => 'The functional unit of the kidney is the:',
                'options' => ['nephron', 'neuron', 'alveolus', 'villus'],
                'correct_answer' => 0,
                'explanation' => 'Nephrons filter blood and form urine.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2024,
                'question_text' => 'The kidney removes mainly:',
                'options' => ['urea', 'oxygen', 'glucose', 'starch'],
                'correct_answer' => 0,
                'explanation' => 'The kidney excretes nitrogenous wastes such as urea.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2023,
                'question_text' => 'The part of the brain responsible for balance and coordination is the:',
                'options' => ['cerebellum', 'cerebrum', 'medulla oblongata', 'hypothalamus'],
                'correct_answer' => 0,
                'explanation' => 'The cerebellum coordinates movement and balance.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Transport and Respiration',
                'year' => 2022,
                'question_text' => 'The reflex centre for many involuntary actions is the:',
                'options' => ['spinal cord', 'cerebrum', 'cerebellum', 'pituitary gland'],
                'correct_answer' => 0,
                'explanation' => 'Reflex actions are coordinated by the spinal cord.',
                'difficulty' => 'medium',
            ],

            // ── Plant Biology and Physiology ──────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2024,
                'question_text' => 'Photosynthesis requires sunlight, water and:',
                'options' => ['carbon dioxide', 'oxygen', 'nitrogen gas', 'glucose'],
                'correct_answer' => 0,
                'explanation' => 'Plants use carbon dioxide and water to manufacture glucose in the presence of light.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2023,
                'question_text' => 'The opening and closing of stomata is controlled by:',
                'options' => ['guard cells', 'root hairs', 'xylem vessels', 'petals'],
                'correct_answer' => 0,
                'explanation' => 'Guard cells regulate the stomatal pore.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2022,
                'question_text' => 'The tissue that transports water and mineral salts in plants is:',
                'options' => ['xylem', 'phloem', 'cambium', 'epidermis'],
                'correct_answer' => 0,
                'explanation' => 'Xylem carries water and dissolved mineral salts from roots to leaves.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2021,
                'question_text' => 'The tissue that transports manufactured food in plants is:',
                'options' => ['phloem', 'xylem', 'epidermis', 'cortex'],
                'correct_answer' => 0,
                'explanation' => 'Phloem transports sugars and other organic nutrients.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2020,
                'question_text' => 'Loss of water vapour from the leaves of a plant is called:',
                'options' => ['transpiration', 'respiration', 'germination', 'pollination'],
                'correct_answer' => 0,
                'explanation' => 'Transpiration occurs mainly through the stomata.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2019,
                'question_text' => 'The green pigment in plants that traps light energy is:',
                'options' => ['chlorophyll', 'haemoglobin', 'carotene', 'anthocyanin'],
                'correct_answer' => 0,
                'explanation' => 'Chlorophyll absorbs light for photosynthesis.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2018,
                'question_text' => 'Root hairs help in:',
                'options' => ['absorption of water and mineral salts', 'pollination', 'seed dispersal', 'fruit formation'],
                'correct_answer' => 0,
                'explanation' => 'Root hairs increase the surface area for absorption.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2024,
                'question_text' => 'For germination to occur, a seed needs water, oxygen and:',
                'options' => ['suitable temperature', 'sunlight always', 'carbon dioxide only', 'fertilizer'],
                'correct_answer' => 0,
                'explanation' => 'Most seeds need warmth, water and oxygen for germination.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2023,
                'question_text' => 'A shoot bending towards light is an example of:',
                'options' => ['phototropism', 'geotropism', 'hydrotropism', 'thigmotropism'],
                'correct_answer' => 0,
                'explanation' => 'Phototropism is growth in response to light.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Plant Biology',
                'year' => 2022,
                'question_text' => 'The hormone that promotes cell elongation in shoots is:',
                'options' => ['auxin', 'insulin', 'adrenaline', 'oestrogen'],
                'correct_answer' => 0,
                'explanation' => 'Auxins stimulate cell elongation and apical dominance.',
                'difficulty' => 'medium',
            ],

            // ── Microorganisms and Health ─────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2024,
                'question_text' => 'Malaria is caused by:',
                'options' => ['Plasmodium', 'Salmonella', 'Rhizopus', 'Amoeba'],
                'correct_answer' => 0,
                'explanation' => 'Malaria is caused by Plasmodium species.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2023,
                'question_text' => 'The vector of malaria is the female:',
                'options' => ['Anopheles mosquito', 'housefly', 'cockroach', 'sandfly'],
                'correct_answer' => 0,
                'explanation' => 'Female Anopheles mosquitoes transmit malaria parasites.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2022,
                'question_text' => 'Antibiotics are effective mainly against:',
                'options' => ['bacteria', 'viruses', 'worms', 'fungal spores only'],
                'correct_answer' => 0,
                'explanation' => 'Antibiotics kill or inhibit bacteria, not viruses.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2021,
                'question_text' => 'HIV attacks the:',
                'options' => ['immune system', 'digestive system', 'skeletal system', 'excretory system'],
                'correct_answer' => 0,
                'explanation' => 'HIV targets cells of the immune system, especially helper T cells.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2020,
                'question_text' => 'Vaccination helps the body to develop:',
                'options' => ['active immunity', 'passive immunity only', 'disease resistance by accident', 'no immunity'],
                'correct_answer' => 0,
                'explanation' => 'Vaccines stimulate the body to produce its own antibodies and memory cells.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2019,
                'question_text' => 'Yeast is commonly used in baking because it:',
                'options' => ['releases carbon dioxide', 'produces antibiotics', 'causes disease', 'makes water hard'],
                'correct_answer' => 0,
                'explanation' => 'Yeast ferments sugar and releases carbon dioxide, which makes dough rise.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2018,
                'question_text' => 'Tuberculosis is caused by a:',
                'options' => ['bacterium', 'virus', 'protozoan', 'fungus'],
                'correct_answer' => 0,
                'explanation' => 'TB is caused by Mycobacterium tuberculosis, a bacterium.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2024,
                'question_text' => 'Cholera is commonly associated with:',
                'options' => ['contaminated water', 'mosquito bites', 'fresh air', 'insect stings'],
                'correct_answer' => 0,
                'explanation' => 'Cholera spreads through contaminated water or food.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2023,
                'question_text' => 'An antiseptic is used to:',
                'options' => ['reduce microorganisms on living tissues', 'sterilize metal instruments completely', 'grow bacteria rapidly', 'increase body temperature'],
                'correct_answer' => 0,
                'explanation' => 'Antiseptics are applied to skin or living tissues to prevent infection.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Microorganisms and Health',
                'year' => 2022,
                'question_text' => 'Sterilization means the:',
                'options' => ['destruction of all microorganisms', 'washing of hands only', 'removal of dirt alone', 'killing of insects only'],
                'correct_answer' => 0,
                'explanation' => 'Sterilization destroys all forms of microbial life.',
                'difficulty' => 'medium',
            ],

            // ── Evolution, Variation and Adaptation ───────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2024,
                'question_text' => 'Differences among individuals of the same species are called:',
                'options' => ['variation', 'mutation', 'adaptation', 'classification'],
                'correct_answer' => 0,
                'explanation' => 'Variation refers to the differences found among individuals of the same species.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2023,
                'question_text' => 'A characteristic that helps an organism survive in its environment is an:',
                'options' => ['adaptation', 'infection', 'enzyme', 'allele'],
                'correct_answer' => 0,
                'explanation' => 'Adaptations improve survival in a particular habitat.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2022,
                'question_text' => 'Natural selection is often described as the survival of the:',
                'options' => ['fittest', 'tallest', 'oldest', 'weakest'],
                'correct_answer' => 0,
                'explanation' => 'Individuals best adapted to the environment are more likely to survive and reproduce.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2021,
                'question_text' => 'The gradual change in living organisms over a long period of time is:',
                'options' => ['evolution', 'respiration', 'excretion', 'digestion'],
                'correct_answer' => 0,
                'explanation' => 'Evolution is the slow change in organisms over generations.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2020,
                'question_text' => 'Continuous variation is best shown by:',
                'options' => ['height', 'blood group', 'tongue rolling', 'ability to taste PTC'],
                'correct_answer' => 0,
                'explanation' => 'Height shows a range of values, making it continuous variation.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2019,
                'question_text' => 'Discontinuous variation is best shown by:',
                'options' => ['blood group', 'weight', 'height', 'length of leaf'],
                'correct_answer' => 0,
                'explanation' => 'Blood group has distinct categories rather than a range.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2018,
                'question_text' => 'The ability of a cactus to reduce water loss is an example of:',
                'options' => ['adaptation', 'mutation', 'competition', 'fertilization'],
                'correct_answer' => 0,
                'explanation' => 'Cactus features such as spines and thick stems are adaptations to dry conditions.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2024,
                'question_text' => 'The process by which plants increase in size and dry mass is called:',
                'options' => ['growth', 'transpiration', 'pollination', 'germination'],
                'correct_answer' => 0,
                'explanation' => 'Growth is an irreversible increase in size and dry mass.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2022,
                'question_text' => 'Complete metamorphosis in insects includes the stage:',
                'options' => ['pupa', 'nymph', 'seed', 'embryo'],
                'correct_answer' => 0,
                'explanation' => 'Complete metamorphosis has egg, larva, pupa and adult stages.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Biology',
                'topic' => 'Evolution and Variation',
                'year' => 2021,
                'question_text' => 'Which of the following is a structural adaptation for aquatic life?',
                'options' => ['streamlined body', 'thick fur', 'large ears', 'sharp claws'],
                'correct_answer' => 0,
                'explanation' => 'A streamlined body reduces resistance in water.',
                'difficulty' => 'easy',
            ],

        ];

        foreach ($questions as $question) {
            Question::create($this->shuffleOptions($question));
        }
    }

    private function shuffleOptions(array $question): array
    {
        $options = $question['options'];
        $correctText = $options[$question['correct_answer']];

        shuffle($options);

        $question['options'] = $options;
        $question['correct_answer'] = array_search($correctText, $options, true);

        return $question;
    }
}
