<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class ChemistrySeeder extends Seeder
{
    public function run(): void
    {
        Question::truncate();

        $questions = [
            // ── Atomic Structure ───────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2024,
                'question_text' => 'Which subatomic particle has a negative charge?',
                'options' => ['Electron', 'Proton', 'Neutron', 'Nucleon'],
                'correct_answer' => 0,
                'explanation' => 'Electrons carry negative charge.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2023,
                'question_text' => 'The atomic number of an element is the number of:',
                'options' => ['protons', 'neutrons', 'electrons and neutrons', 'nucleons'],
                'correct_answer' => 0,
                'explanation' => 'Atomic number equals the number of protons in the nucleus.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2022,
                'question_text' => 'Which of the following is a noble gas?',
                'options' => ['Neon', 'Sodium', 'Chlorine', 'Magnesium'],
                'correct_answer' => 0,
                'explanation' => 'Neon is a Group 18 noble gas.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2021,
                'question_text' => 'An isotope of an element has the same number of:',
                'options' => ['protons but different neutrons', 'neutrons but different protons', 'electrons and neutrons only', 'nucleons only'],
                'correct_answer' => 0,
                'explanation' => 'Isotopes have the same proton number but different neutron numbers.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2020,
                'question_text' => 'The relative atomic mass of chlorine is about 35.5 because chlorine exists as:',
                'options' => ['a mixture of isotopes', 'one isotope only', 'a compound', 'a mixture of ions'],
                'correct_answer' => 0,
                'explanation' => 'Natural chlorine is mainly a mixture of chlorine-35 and chlorine-37 isotopes.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2019,
                'question_text' => 'The maximum number of electrons in the first shell is:',
                'options' => ['2', '8', '18', '32'],
                'correct_answer' => 0,
                'explanation' => 'The first shell can hold only 2 electrons.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2018,
                'question_text' => 'Which particle is found in the nucleus of an atom?',
                'options' => ['Proton', 'Electron', 'Photon', 'Alpha ray'],
                'correct_answer' => 0,
                'explanation' => 'Protons and neutrons are found in the nucleus.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2024,
                'question_text' => 'The electronic configuration of sodium is:',
                'options' => ['2,8,1', '2,7,2', '2,8,2', '2,6,1'],
                'correct_answer' => 0,
                'explanation' => 'Sodium has 11 electrons arranged as 2,8,1.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2023,
                'question_text' => 'What is the charge on a proton?',
                'options' => ['+1', '0', '-1', '+2'],
                'correct_answer' => 0,
                'explanation' => 'A proton carries a positive charge of +1.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Atomic Structure',
                'year' => 2022,
                'question_text' => 'The mass number of an atom is the sum of:',
                'options' => ['protons and neutrons', 'protons and electrons', 'neutrons and electrons', 'electrons only'],
                'correct_answer' => 0,
                'explanation' => 'Mass number = protons + neutrons.',
                'difficulty' => 'easy',
            ],

            // ── Periodic Table and Periodicity ─────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2024,
                'question_text' => 'Elements in the same group of the periodic table have the same number of:',
                'options' => ['valence electrons', 'neutrons', 'protons', 'electron shells'],
                'correct_answer' => 0,
                'explanation' => 'Elements in the same group have similar valence electron arrangements.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2023,
                'question_text' => 'Which element is the most electropositive?',
                'options' => ['Cesium', 'Fluorine', 'Oxygen', 'Chlorine'],
                'correct_answer' => 0,
                'explanation' => 'Electropositivity increases down a group and to the left of the periodic table.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2022,
                'question_text' => 'Which property generally increases across a period from left to right?',
                'options' => ['electronegativity', 'atomic radius', 'metallic character', 'reactivity of metals'],
                'correct_answer' => 0,
                'explanation' => 'Electronegativity generally increases across a period.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2021,
                'question_text' => 'Which element has the largest atomic radius among these?',
                'options' => ['Potassium', 'Sodium', 'Lithium', 'Rubidium'],
                'correct_answer' => 3,
                'explanation' => 'Atomic radius increases down Group 1, so rubidium is largest.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2020,
                'question_text' => 'The halogens are found in Group:',
                'options' => ['17', '1', '2', '18'],
                'correct_answer' => 0,
                'explanation' => 'Halogens are Group 17 elements.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2019,
                'question_text' => 'Which of these is a transition metal?',
                'options' => ['Iron', 'Sodium', 'Calcium', 'Argon'],
                'correct_answer' => 0,
                'explanation' => 'Iron is a transition metal.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2018,
                'question_text' => 'The inert gases are located in Group:',
                'options' => ['18', '1', '2', '16'],
                'correct_answer' => 0,
                'explanation' => 'Noble gases are in Group 18.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2024,
                'question_text' => 'Which of the following is a non-metal?',
                'options' => ['Sulfur', 'Iron', 'Copper', 'Zinc'],
                'correct_answer' => 0,
                'explanation' => 'Sulfur is a non-metal.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2023,
                'question_text' => 'Atomic size generally decreases across a period because of increased:',
                'options' => ['nuclear charge', 'number of shells', 'shielding only', 'neutron number only'],
                'correct_answer' => 0,
                'explanation' => 'Increasing nuclear charge pulls electrons closer to the nucleus.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2022,
                'question_text' => 'Which element is most likely to form a 1+ ion?',
                'options' => ['Sodium', 'Chlorine', 'Oxygen', 'Magnesium'],
                'correct_answer' => 0,
                'explanation' => 'Sodium is a Group 1 metal and usually forms Na+.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Periodic Table',
                'year' => 2021,
                'question_text' => 'The most reactive group of metals is the:',
                'options' => ['alkali metals', 'noble gases', 'halogens', 'metalloids'],
                'correct_answer' => 0,
                'explanation' => 'Alkali metals are highly reactive because they lose one electron easily.',
                'difficulty' => 'medium',
            ],

            // ── Chemical Bonding ───────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2024,
                'question_text' => 'An ionic bond is formed by:',
                'options' => ['transfer of electrons', 'sharing of electrons', 'sharing of protons', 'transfer of neutrons'],
                'correct_answer' => 0,
                'explanation' => 'Ionic bonding involves electron transfer between atoms.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2023,
                'question_text' => 'A covalent bond is formed by:',
                'options' => ['sharing of electrons', 'transfer of electrons', 'transfer of protons', 'loss of neutrons'],
                'correct_answer' => 0,
                'explanation' => 'Covalent bonds involve shared electron pairs.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2022,
                'question_text' => 'Which compound is likely to have ionic bonding?',
                'options' => ['NaCl', 'CH4', 'H2', 'O2'],
                'correct_answer' => 0,
                'explanation' => 'Sodium chloride is formed between a metal and a non-metal.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2021,
                'question_text' => 'Which intermolecular force is present in all molecules?',
                'options' => ['London dispersion force', 'Hydrogen bonding', 'Ionic bonding', 'Metallic bonding'],
                'correct_answer' => 0,
                'explanation' => 'London dispersion forces occur in all molecules and atoms.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2020,
                'question_text' => 'Hydrogen bonding is strongest in molecules containing hydrogen bonded to:',
                'options' => ['N, O or F', 'C only', 'Na only', 'Cl only'],
                'correct_answer' => 0,
                'explanation' => 'Hydrogen bonding occurs when H is bonded to highly electronegative atoms such as N, O or F.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2019,
                'question_text' => 'The bond in a molecule of hydrogen gas is:',
                'options' => ['covalent', 'ionic', 'metallic', 'hydrogen'],
                'correct_answer' => 0,
                'explanation' => 'Two hydrogen atoms share electrons to form a covalent bond.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2018,
                'question_text' => 'Which compound conducts electricity when molten?',
                'options' => ['NaCl', 'Sugar', 'Ethanol', 'Paraffin'],
                'correct_answer' => 0,
                'explanation' => 'Molten ionic compounds conduct because ions are free to move.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2024,
                'question_text' => 'A metal bond is best described as:',
                'options' => ['positive ions in a sea of electrons', 'sharing of electron pairs between non-metals', 'transfer of electrons to oxygen', 'sharing of neutrons'],
                'correct_answer' => 0,
                'explanation' => 'Metallic bonding consists of positive ions surrounded by delocalized electrons.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2023,
                'question_text' => 'Which is the correct order of bond strength?',
                'options' => ['covalent > hydrogen > van der Waals', 'hydrogen > covalent > ionic', 'van der Waals > ionic > covalent', 'ionic > hydrogen > covalent'],
                'correct_answer' => 0,
                'explanation' => 'Covalent bonds are generally stronger than hydrogen and van der Waals forces.',
                'difficulty' => 'hard',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2022,
                'question_text' => 'Which of these molecules is non-polar?',
                'options' => ['CO2', 'H2O', 'NH3', 'HCl'],
                'correct_answer' => 0,
                'explanation' => 'CO2 is linear and symmetrical, so its bond dipoles cancel.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2021,
                'question_text' => 'Which substance is most likely to have a giant covalent structure?',
                'options' => ['Diamond', 'Sodium chloride', 'Copper', 'Methane'],
                'correct_answer' => 0,
                'explanation' => 'Diamond is a giant covalent lattice.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Chemical Bonding',
                'year' => 2020,
                'question_text' => 'The shape of methane is:',
                'options' => ['tetrahedral', 'linear', 'trigonal planar', 'bent'],
                'correct_answer' => 0,
                'explanation' => 'Methane has four bonding pairs around carbon, giving a tetrahedral shape.',
                'difficulty' => 'medium',
            ],

            // ── Stoichiometry and Mole Concept ─────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2024,
                'question_text' => 'How many moles are in 44 g of CO2? (C=12, O=16)',
                'options' => ['1 mol', '2 mol', '0.5 mol', '4 mol'],
                'correct_answer' => 0,
                'explanation' => 'Molar mass of CO2 = 44 g/mol, so 44 g is 1 mol.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2023,
                'question_text' => 'The molar mass of H2SO4 is:',
                'options' => ['98 g/mol', '96 g/mol', '100 g/mol', '102 g/mol'],
                'correct_answer' => 0,
                'explanation' => 'H2SO4 = 2 + 32 + 64 = 98 g/mol.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2022,
                'question_text' => 'At room conditions, 1 mole of any gas occupies about:',
                'options' => ['24 dm3', '22 dm3', '11 dm3', '12 dm3'],
                'correct_answer' => 0,
                'explanation' => 'At room temperature and pressure, one mole of gas occupies about 24 dm3.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2021,
                'question_text' => 'How many molecules are in 1 mole of a substance?',
                'options' => ['6.02 x 10^23', '3.01 x 10^23', '1.00 x 10^23', '9.81 x 10^23'],
                'correct_answer' => 0,
                'explanation' => 'One mole contains Avogadro number of particles.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2020,
                'question_text' => 'What is the mass of 2 moles of NaOH? (Na=23, O=16, H=1)',
                'options' => ['80 g', '40 g', '60 g', '100 g'],
                'correct_answer' => 0,
                'explanation' => 'Molar mass of NaOH = 40 g/mol, so 2 moles = 80 g.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2019,
                'question_text' => 'The empirical formula of a compound is the:',
                'options' => ['simplest whole-number ratio of atoms', 'exact number of atoms in a molecule', 'molecular structure', 'formula of a salt'],
                'correct_answer' => 0,
                'explanation' => 'Empirical formula gives the simplest ratio of atoms present.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2018,
                'question_text' => 'The molecular formula of a compound is:',
                'options' => ['the actual number of atoms in a molecule', 'the simplest ratio only', 'a charge balance', 'a structural sketch'],
                'correct_answer' => 0,
                'explanation' => 'Molecular formula shows the actual number of each atom in a molecule.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2024,
                'question_text' => 'In the equation 2H2 + O2 -> 2H2O, the mole ratio of H2 to O2 is:',
                'options' => ['2:1', '1:2', '1:1', '2:2'],
                'correct_answer' => 0,
                'explanation' => 'The coefficients show a 2:1 ratio.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2023,
                'question_text' => 'The number of atoms in 1 mole of oxygen atoms is:',
                'options' => ['6.02 x 10^23', '3.01 x 10^23', '1.00 x 10^24', '24'],
                'correct_answer' => 0,
                'explanation' => 'One mole always contains Avogadro number of particles.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2022,
                'question_text' => 'Which term refers to the mass of one mole of a substance?',
                'options' => ['molar mass', 'formula mass', 'relative density', 'atomicity'],
                'correct_answer' => 0,
                'explanation' => 'Molar mass is mass per mole.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Stoichiometry',
                'year' => 2021,
                'question_text' => 'The volume occupied by 2 moles of gas at RTP is about:',
                'options' => ['48 dm3', '24 dm3', '22 dm3', '12 dm3'],
                'correct_answer' => 0,
                'explanation' => 'At RTP, one mole occupies 24 dm3, so 2 moles occupy 48 dm3.',
                'difficulty' => 'easy',
            ],

            // ── Acids, Bases and Salts ─────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2024,
                'question_text' => 'A solution with pH 2 is:',
                'options' => ['acidic', 'neutral', 'basic', 'amphoteric'],
                'correct_answer' => 0,
                'explanation' => 'pH below 7 indicates an acidic solution.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2023,
                'question_text' => 'Which of these is a strong acid?',
                'options' => ['Hydrochloric acid', 'Ethanoic acid', 'Carbonic acid', 'Citric acid'],
                'correct_answer' => 0,
                'explanation' => 'Hydrochloric acid is a strong acid.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2022,
                'question_text' => 'Which indicator turns blue in alkali?',
                'options' => ['Red litmus', 'Methyl orange', 'Phenolphthalein', 'Universal indicator'],
                'correct_answer' => 0,
                'explanation' => 'Red litmus turns blue in alkaline solution.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2021,
                'question_text' => 'Phenolphthalein is pink in:',
                'options' => ['alkali', 'acid', 'pure water', 'salt solution only'],
                'correct_answer' => 0,
                'explanation' => 'Phenolphthalein is colorless in acid and pink in alkali.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2020,
                'question_text' => 'The salt formed when hydrochloric acid reacts with sodium hydroxide is:',
                'options' => ['sodium chloride', 'sodium sulfate', 'sodium carbonate', 'sodium nitrate'],
                'correct_answer' => 0,
                'explanation' => 'HCl + NaOH -> NaCl + H2O.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2019,
                'question_text' => 'An acid is a substance that donates:',
                'options' => ['H+ ions', 'OH- ions', 'electrons only', 'neutrons'],
                'correct_answer' => 0,
                'explanation' => 'According to the Arrhenius/Brønsted concept, acids donate H+ ions.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2018,
                'question_text' => 'A base is a substance that accepts:',
                'options' => ['H+ ions', 'Cl- ions', 'neutrons', 'protons only'],
                'correct_answer' => 0,
                'explanation' => 'Bases accept hydrogen ions in the Brønsted-Lowry definition.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2024,
                'question_text' => 'Which oxide is acidic?',
                'options' => ['SO2', 'Na2O', 'MgO', 'CaO'],
                'correct_answer' => 0,
                'explanation' => 'Non-metal oxides such as SO2 are generally acidic.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2023,
                'question_text' => 'The pH of neutral pure water is about:',
                'options' => ['7', '1', '14', '4'],
                'correct_answer' => 0,
                'explanation' => 'Pure water is neutral and has pH 7.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2022,
                'question_text' => 'Which of these is a basic oxide?',
                'options' => ['MgO', 'CO2', 'SO3', 'NO2'],
                'correct_answer' => 0,
                'explanation' => 'Metal oxides such as MgO are basic.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Acids and Bases',
                'year' => 2021,
                'question_text' => 'A neutralization reaction produces:',
                'options' => ['salt and water', 'carbon dioxide and water', 'acid and base', 'salt and hydrogen'],
                'correct_answer' => 0,
                'explanation' => 'Acid + base -> salt + water.',
                'difficulty' => 'easy',
            ],

            // ── Separation Techniques ──────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2024,
                'question_text' => 'Which method is best for separating sand from water?',
                'options' => ['filtration', 'sublimation', 'chromatography', 'distillation'],
                'correct_answer' => 0,
                'explanation' => 'Filtration separates an insoluble solid from a liquid.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2023,
                'question_text' => 'Which method is used to separate the components of ink?',
                'options' => ['paper chromatography', 'decantation', 'sieving', 'evaporation'],
                'correct_answer' => 0,
                'explanation' => 'Chromatography separates dyes based on different solubilities and adsorption.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2022,
                'question_text' => 'The technique used to separate crude oil into fractions is:',
                'options' => ['fractional distillation', 'sublimation', 'filtration', 'decantation'],
                'correct_answer' => 0,
                'explanation' => 'Crude oil components are separated by fractional distillation.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2021,
                'question_text' => 'A mixture of iron filings and sulfur can be separated using a:',
                'options' => ['magnet', 'filter paper', 'funnel', 'evaporating dish'],
                'correct_answer' => 0,
                'explanation' => 'Iron is magnetic, sulfur is not.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2020,
                'question_text' => 'The method used to obtain pure water from salt solution is:',
                'options' => ['simple distillation', 'filtration', 'sieving', 'magnetization'],
                'correct_answer' => 0,
                'explanation' => 'Simple distillation separates water from dissolved salts.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2019,
                'question_text' => 'Which method separates substances based on different boiling points?',
                'options' => ['distillation', 'sieving', 'decantation', 'sedimentation'],
                'correct_answer' => 0,
                'explanation' => 'Distillation relies on differences in boiling points.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2018,
                'question_text' => 'The process of removing the solvent from a solution to leave the solute behind is:',
                'options' => ['evaporation', 'filtration', 'crystallization', 'centrifugation'],
                'correct_answer' => 0,
                'explanation' => 'Evaporation removes the solvent and leaves the dissolved solid.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2024,
                'question_text' => 'A centrifuge is used to separate:',
                'options' => ['suspended solids from liquids', 'dyes from ink', 'liquids with similar boiling points', 'salt from water'],
                'correct_answer' => 0,
                'explanation' => 'Centrifugation is useful for separating fine suspended solids.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2023,
                'question_text' => 'The apparatus used for separating miscible liquids is a:',
                'options' => ['fractionating column', 'filter funnel', 'separating funnel', 'gas jar'],
                'correct_answer' => 0,
                'explanation' => 'A fractionating column improves separation of miscible liquids with close boiling points.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2022,
                'question_text' => 'Which method is used to obtain salt crystals from sea water?',
                'options' => ['evaporation and crystallization', 'sublimation', 'magnetic separation', 'filtration only'],
                'correct_answer' => 0,
                'explanation' => 'Removing water leaves salt crystals behind.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Separation Techniques',
                'year' => 2021,
                'question_text' => 'Which of these is an insoluble solid-liquid separation method?',
                'options' => ['filtration', 'distillation', 'fractional distillation', 'paper chromatography'],
                'correct_answer' => 0,
                'explanation' => 'Filtration removes insoluble solids from liquids.',
                'difficulty' => 'easy',
            ],

            // ── States of Matter and Gas Laws ──────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2024,
                'question_text' => 'Which state of matter has a definite volume but no definite shape?',
                'options' => ['Liquid', 'Solid', 'Gas', 'Plasma'],
                'correct_answer' => 0,
                'explanation' => 'Liquids take the shape of their containers but keep a fixed volume.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2023,
                'question_text' => 'The process by which a solid changes directly into a gas is:',
                'options' => ['sublimation', 'melting', 'freezing', 'condensation'],
                'correct_answer' => 0,
                'explanation' => 'Sublimation is the direct change from solid to gas.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2022,
                'question_text' => 'A gas is easily compressed because its particles are:',
                'options' => ['far apart', 'very large', 'fixed in place', 'strongly bonded'],
                'correct_answer' => 0,
                'explanation' => 'Gas particles are widely spaced with lots of empty space.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2021,
                'question_text' => 'The movement of gas particles from a region of higher concentration to lower concentration is:',
                'options' => ['diffusion', 'condensation', 'sublimation', 'deposition'],
                'correct_answer' => 0,
                'explanation' => 'Diffusion occurs as gas particles spread out.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2020,
                'question_text' => 'Boyle law states that for a fixed mass of gas at constant temperature, pressure is inversely proportional to:',
                'options' => ['volume', 'temperature', 'mass', 'density'],
                'correct_answer' => 0,
                'explanation' => 'Boyle law: P is inversely proportional to V.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2019,
                'question_text' => 'Charles law states that at constant pressure, the volume of a gas is directly proportional to:',
                'options' => ['temperature', 'pressure', 'mass', 'moles only'],
                'correct_answer' => 0,
                'explanation' => 'Charles law links volume and absolute temperature.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2018,
                'question_text' => 'The kinetic theory of matter assumes that particles are in constant:',
                'options' => ['motion', 'rest', 'combustion', 'repulsion only'],
                'correct_answer' => 0,
                'explanation' => 'Particles are always moving in solids, liquids and gases.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2024,
                'question_text' => 'The gas law represented by PV = constant at constant temperature is:',
                'options' => ['Boyle law', 'Charles law', 'Avogadro law', 'Dalton law'],
                'correct_answer' => 0,
                'explanation' => 'PV = constant is Boyle law.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2023,
                'question_text' => 'The temperature scale used in gas calculations is:',
                'options' => ['Kelvin', 'Celsius', 'Fahrenheit', 'Rankine'],
                'correct_answer' => 0,
                'explanation' => 'Absolute temperature must be used, measured in Kelvin.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2022,
                'question_text' => 'Which state of matter has particles packed closely in a fixed arrangement?',
                'options' => ['Solid', 'Liquid', 'Gas', 'Plasma'],
                'correct_answer' => 0,
                'explanation' => 'Solid particles occupy fixed positions and vibrate about them.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'States of Matter',
                'year' => 2021,
                'question_text' => 'Which of the following best explains pressure in a gas?',
                'options' => ['collisions of particles with container walls', 'weight of particles only', 'attraction between particles', 'size of particles only'],
                'correct_answer' => 0,
                'explanation' => 'Gas pressure is caused by particle collisions with the container walls.',
                'difficulty' => 'medium',
            ],

            // ── Organic Chemistry ──────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2024,
                'question_text' => 'The general formula of alkanes is:',
                'options' => ['CnH2n+2', 'CnH2n', 'CnH2n-2', 'CnHn'],
                'correct_answer' => 0,
                'explanation' => 'Alkanes are saturated hydrocarbons with formula CnH2n+2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2023,
                'question_text' => 'Which of these is an alkene?',
                'options' => ['Ethene', 'Ethane', 'Methane', 'Propane'],
                'correct_answer' => 0,
                'explanation' => 'Ethene contains a carbon-carbon double bond.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2022,
                'question_text' => 'The functional group in alcohols is:',
                'options' => ['-OH', '-COOH', '-CHO', '-NH2'],
                'correct_answer' => 0,
                'explanation' => 'Alcohols contain the hydroxyl functional group.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2021,
                'question_text' => 'The homologous series with general formula CnH2n+1OH is:',
                'options' => ['alcohols', 'alkanes', 'alkynes', 'ketones'],
                'correct_answer' => 0,
                'explanation' => 'This is the general formula for monohydric alcohols.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2020,
                'question_text' => 'Complete combustion of hydrocarbons produces:',
                'options' => ['carbon dioxide and water', 'carbon monoxide and water', 'soot and hydrogen', 'methane and oxygen'],
                'correct_answer' => 0,
                'explanation' => 'Complete combustion yields carbon dioxide and water.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2019,
                'question_text' => 'The IUPAC name of CH3CH2OH is:',
                'options' => ['ethanol', 'methanoic acid', 'ethene', 'ethanal'],
                'correct_answer' => 0,
                'explanation' => 'CH3CH2OH is ethanol.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2018,
                'question_text' => 'The functional group in carboxylic acids is:',
                'options' => ['-COOH', '-OH', '-CHO', '-CO-'],
                'correct_answer' => 0,
                'explanation' => 'Carboxylic acids contain the carboxyl group.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2024,
                'question_text' => 'Which compound is an ester?',
                'options' => ['Ethyl ethanoate', 'Ethanol', 'Ethanoic acid', 'Ethene'],
                'correct_answer' => 0,
                'explanation' => 'Ethyl ethanoate is an ester.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2023,
                'question_text' => 'Polymerization of ethene produces:',
                'options' => ['polyethene', 'ethanol', 'ethanoic acid', 'propane'],
                'correct_answer' => 0,
                'explanation' => 'Ethene molecules join to form polyethene.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2022,
                'question_text' => 'Cracking in petroleum refining is used to:',
                'options' => ['produce smaller hydrocarbon molecules', 'remove sulfur from oil', 'increase the boiling point of fuel', 'form alcohols'],
                'correct_answer' => 0,
                'explanation' => 'Cracking breaks large hydrocarbons into smaller ones.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Organic Chemistry',
                'year' => 2021,
                'question_text' => 'Which reagent can test for unsaturation in an alkene?',
                'options' => ['Bromine water', 'Litmus paper', 'Silver nitrate', 'Universal indicator'],
                'correct_answer' => 0,
                'explanation' => 'Bromine water is decolorized by alkenes.',
                'difficulty' => 'medium',
            ],

            // ── Electrolysis and Redox ────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2024,
                'question_text' => 'Electrolysis is the decomposition of a compound by passing:',
                'options' => ['electric current', 'heat only', 'light only', 'pressure only'],
                'correct_answer' => 0,
                'explanation' => 'An electric current causes ionic compounds to break down.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2023,
                'question_text' => 'The positive electrode in electrolysis is the:',
                'options' => ['anode', 'cathode', 'electrolyte', 'salt bridge'],
                'correct_answer' => 0,
                'explanation' => 'The anode is the positive electrode during electrolysis.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2022,
                'question_text' => 'The negative electrode in electrolysis is the:',
                'options' => ['cathode', 'anode', 'electrolyte', 'salt bridge'],
                'correct_answer' => 0,
                'explanation' => 'The cathode is the negative electrode during electrolysis.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2021,
                'question_text' => 'During electrolysis of molten lead(II) bromide, the product at the cathode is:',
                'options' => ['lead', 'bromine', 'oxygen', 'hydrogen'],
                'correct_answer' => 0,
                'explanation' => 'Lead ions are reduced at the cathode to lead metal.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2020,
                'question_text' => 'During electrolysis of acidified water, the gas produced at the cathode is:',
                'options' => ['hydrogen', 'oxygen', 'chlorine', 'nitrogen'],
                'correct_answer' => 0,
                'explanation' => 'Hydrogen ions are reduced to hydrogen gas at the cathode.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2019,
                'question_text' => 'Oxidation is best defined as:',
                'options' => ['loss of electrons', 'gain of electrons', 'gain of protons', 'loss of neutrons'],
                'correct_answer' => 0,
                'explanation' => 'Oxidation is loss of electrons.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2018,
                'question_text' => 'Reduction is best defined as:',
                'options' => ['gain of electrons', 'loss of electrons', 'gain of neutrons', 'loss of protons'],
                'correct_answer' => 0,
                'explanation' => 'Reduction is gain of electrons.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2024,
                'question_text' => 'Rusting of iron is an example of:',
                'options' => ['oxidation', 'reduction', 'neutralization', 'distillation'],
                'correct_answer' => 0,
                'explanation' => 'Rusting involves oxidation of iron.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2023,
                'question_text' => 'The process used in the extraction of aluminum is:',
                'options' => ['electrolysis', 'filtration', 'fractional distillation', 'crystallization'],
                'correct_answer' => 0,
                'explanation' => 'Aluminum is extracted from its ore by electrolysis.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2022,
                'question_text' => 'Which ions move to the cathode during electrolysis?',
                'options' => ['cations', 'anions', 'neutrons', 'atoms only'],
                'correct_answer' => 0,
                'explanation' => 'Positive ions (cations) move to the cathode.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Electrolysis',
                'year' => 2021,
                'question_text' => 'Which ions move to the anode during electrolysis?',
                'options' => ['anions', 'cations', 'metals only', 'neutral atoms'],
                'correct_answer' => 0,
                'explanation' => 'Negative ions (anions) move to the anode.',
                'difficulty' => 'easy',
            ],

            // ── Thermochemistry and Energetics ────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2024,
                'question_text' => 'A reaction that releases heat is described as:',
                'options' => ['exothermic', 'endothermic', 'neutral', 'reversible'],
                'correct_answer' => 0,
                'explanation' => 'Exothermic reactions release heat to the surroundings.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2023,
                'question_text' => 'A reaction that absorbs heat is:',
                'options' => ['endothermic', 'exothermic', 'spontaneous', 'combustion'],
                'correct_answer' => 0,
                'explanation' => 'Endothermic reactions absorb heat from the surroundings.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2022,
                'question_text' => 'The unit of energy commonly used in chemistry is:',
                'options' => ['joule', 'newton', 'watt', 'volt'],
                'correct_answer' => 0,
                'explanation' => 'Energy is measured in joules.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2021,
                'question_text' => 'The heat change when 1 mole of a substance burns completely is called:',
                'options' => ['enthalpy of combustion', 'enthalpy of formation', 'enthalpy of neutralization', 'ionization energy'],
                'correct_answer' => 0,
                'explanation' => 'Combustion enthalpy is the heat released when one mole burns completely in oxygen.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2020,
                'question_text' => 'The heat absorbed when one mole of a compound is formed from its elements is:',
                'options' => ['enthalpy of formation', 'enthalpy of combustion', 'activation energy', 'lattice energy'],
                'correct_answer' => 0,
                'explanation' => 'Enthalpy of formation refers to formation from elements in their standard states.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2019,
                'question_text' => 'An exothermic reaction usually causes the temperature of the surroundings to:',
                'options' => ['increase', 'decrease', 'remain constant', 'become zero'],
                'correct_answer' => 0,
                'explanation' => 'Heat released warms the surroundings.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2018,
                'question_text' => 'Endothermic reactions are often characterized by:',
                'options' => ['temperature drop in surroundings', 'heat release to surroundings', 'no energy change', 'formation of metals only'],
                'correct_answer' => 0,
                'explanation' => 'Heat is absorbed from the surroundings, lowering their temperature.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2024,
                'question_text' => 'Which process is exothermic?',
                'options' => ['freezing of water', 'melting of ice', 'evaporation of water', 'sublimation of iodine'],
                'correct_answer' => 0,
                'explanation' => 'Freezing releases latent heat to the surroundings.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2023,
                'question_text' => 'The energy needed to start a chemical reaction is called:',
                'options' => ['activation energy', 'enthalpy', 'entropy', 'heat capacity'],
                'correct_answer' => 0,
                'explanation' => 'Activation energy is the minimum energy required to initiate a reaction.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Chemistry',
                'topic' => 'Thermochemistry',
                'year' => 2022,
                'question_text' => 'The law of conservation of mass states that mass is:',
                'options' => ['neither created nor destroyed in a chemical reaction', 'always increased', 'always reduced', 'converted into energy completely'],
                'correct_answer' => 0,
                'explanation' => 'Total mass remains constant in a closed system during a reaction.',
                'difficulty' => 'easy',
            ],
        ];

        foreach ($questions as $question) {
            Question::create($this->shuffleOptions($question));
        }
    }

    private function shuffleOptions(array $question): array
    {
        $options = $question['options'];
        $correctText = $options[$question['correct_answer']];

        shuffle($options);

        $question['options'] = $options;
        $question['correct_answer'] = array_search($correctText, $options, true);

        return $question;
    }
}
