<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class EnglishSeeder extends Seeder
{
    public function run(): void
    {
        Question::truncate();

        $questions = [
            // ── Comprehension and Inference ────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2024,
                'question_text' => 'The boy sold his bicycle to pay his fees. This suggests that he was:',
                'options' => ['in financial need', 'careless with money', 'unhappy with school', 'trying to impress friends'],
                'correct_answer' => 0,
                'explanation' => 'Selling a bicycle to pay fees suggests he needed money urgently.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2023,
                'question_text' => 'An article warning readers about the dangers of excessive phone use is mainly intended to:',
                'options' => ['warn readers', 'entertain readers', 'advertise phones', 'praise technology'],
                'correct_answer' => 0,
                'explanation' => 'The writer is trying to caution the audience, so the purpose is to warn.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2022,
                'question_text' => 'The statement "At last, the lazy workers arrived" expresses:',
                'options' => ['sarcasm', 'admiration', 'fear', 'joy'],
                'correct_answer' => 0,
                'explanation' => 'The word "lazy" shows the speaker is being sarcastic.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2021,
                'question_text' => 'If a room is dark and the children whisper, the mood is likely:',
                'options' => ['tense and quiet', 'joyful and noisy', 'formal and polite', 'bright and cheerful'],
                'correct_answer' => 0,
                'explanation' => 'Darkness and whispering create a tense, quiet mood.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2020,
                'question_text' => 'The company decided to cut corners. This means it:',
                'options' => ['did the work cheaply or badly', 'made the building round', 'spent more money', 'improved the design'],
                'correct_answer' => 0,
                'explanation' => 'To cut corners means to do something in the easiest, cheapest, or careless way.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2019,
                'question_text' => 'Ada and Ngozi won the prize because they studied hard. The pronoun "they" refers to:',
                'options' => ['Ada and Ngozi', 'the prize', 'the teachers', 'the school'],
                'correct_answer' => 0,
                'explanation' => 'The pronoun refers to the two girls mentioned earlier.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2018,
                'question_text' => 'He closed the door gently after the argument. This suggests that he wanted to:',
                'options' => ['avoid more noise', 'break the door', 'invite others in', 'show anger openly'],
                'correct_answer' => 0,
                'explanation' => 'Closing the door gently suggests he wanted calm and quiet.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2024,
                'question_text' => 'A passage that emphasizes timely planting and weeding is mainly about:',
                'options' => ['better farm productivity', 'city traffic', 'school discipline', 'online learning'],
                'correct_answer' => 0,
                'explanation' => 'Timely planting and weeding are farming practices that improve yield.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2023,
                'question_text' => 'The author describes the team as determined and focused. The attitude is:',
                'options' => ['approving', 'mocking', 'indifferent', 'hostile'],
                'correct_answer' => 0,
                'explanation' => 'The description shows the author admires the team.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Comprehension',
                'year' => 2022,
                'question_text' => 'Which sentence best summarizes a passage about clean water and sanitation?',
                'options' => ['Clean water and sanitation are important for public health.', 'People should never bathe.', 'Only rich communities need water.', 'Sanitation has no effect on health.'],
                'correct_answer' => 0,
                'explanation' => 'That sentence captures the main idea without unnecessary detail.',
                'difficulty' => 'medium',
            ],

            // ── Grammar and Usage ──────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2024,
                'question_text' => 'Neither John nor his friends ___ present.',
                'options' => ['are', 'is', 'was', 'be'],
                'correct_answer' => 0,
                'explanation' => 'The verb agrees with the nearer subject, "friends", which is plural.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2023,
                'question_text' => 'By the time we arrived, she ___ gone home.',
                'options' => ['had', 'has', 'have', 'was'],
                'correct_answer' => 0,
                'explanation' => 'The past perfect tense is needed to show an earlier past action.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2022,
                'question_text' => 'Choose the correct preposition: She is interested ___ music.',
                'options' => ['in', 'on', 'at', 'with'],
                'correct_answer' => 0,
                'explanation' => 'The correct collocation is interested in.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2021,
                'question_text' => 'He said, "I am tired." The reported speech is:',
                'options' => ['He said that he was tired.', 'He said that I am tired.', 'He says that he was tired.', 'He said that he is tired.'],
                'correct_answer' => 0,
                'explanation' => 'In reported speech, the present tense changes to the past tense.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2020,
                'question_text' => 'The girl ___ won the race is my sister.',
                'options' => ['who', 'whom', 'whose', 'which'],
                'correct_answer' => 0,
                'explanation' => 'Who is used for the subject of the relative clause.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2019,
                'question_text' => 'The pupils wrote the test yesterday. The passive voice is:',
                'options' => ['The test was written by the pupils yesterday.', 'The test is written by the pupils yesterday.', 'The pupils are written by the test yesterday.', 'The test wrote the pupils yesterday.'],
                'correct_answer' => 0,
                'explanation' => 'The object becomes the subject and the verb is changed to the passive form.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2018,
                'question_text' => 'You are coming, ___?',
                'options' => ["aren't you", "are you", "won't you", "isn't you"],
                'correct_answer' => 0,
                'explanation' => 'The question tag must match the auxiliary verb and subject.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2024,
                'question_text' => 'Each of the players ___ given a medal.',
                'options' => ['was', 'were', 'have', 'are'],
                'correct_answer' => 0,
                'explanation' => 'Each takes a singular verb.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2023,
                'question_text' => 'Choose the correct sentence:',
                'options' => ['However, we left early.', 'However we left early.', 'We however left early.', 'We left however early.'],
                'correct_answer' => 0,
                'explanation' => 'However is a conjunctive adverb and should be followed by a comma when it begins a sentence.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Grammar',
                'year' => 2022,
                'question_text' => 'By next week, I ___ finished the project.',
                'options' => ['will have', 'had', 'have', 'am'],
                'correct_answer' => 0,
                'explanation' => 'The future perfect tense is needed.',
                'difficulty' => 'medium',
            ],

            // ── Vocabulary ─────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2024,
                'question_text' => 'What is the synonym of "scarce"?',
                'options' => ['rare', 'plentiful', 'heavy', 'certain'],
                'correct_answer' => 0,
                'explanation' => 'Scarce means in short supply or rare.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2023,
                'question_text' => 'What is the antonym of "expand"?',
                'options' => ['shrink', 'increase', 'extend', 'widen'],
                'correct_answer' => 0,
                'explanation' => 'Expand means to become larger; its opposite is shrink.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2022,
                'question_text' => 'The word "persistent" means:',
                'options' => ['determined and continuing', 'careless', 'fearful', 'silent'],
                'correct_answer' => 0,
                'explanation' => 'Persistent means continuing firmly despite difficulty.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2021,
                'question_text' => 'What is the synonym of "obvious"?',
                'options' => ['clear', 'hidden', 'faint', 'rare'],
                'correct_answer' => 0,
                'explanation' => 'Obvious means easy to see or understand.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2020,
                'question_text' => 'What is the antonym of "generous"?',
                'options' => ['stingy', 'kind', 'rich', 'friendly'],
                'correct_answer' => 0,
                'explanation' => 'The opposite of generous is stingy.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2019,
                'question_text' => 'What does "brief" mean?',
                'options' => ['short', 'difficult', 'heavy', 'quickly'],
                'correct_answer' => 0,
                'explanation' => 'Brief means short in time or length.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2018,
                'question_text' => 'What is the synonym of "ancient"?',
                'options' => ['old', 'new', 'modern', 'bright'],
                'correct_answer' => 0,
                'explanation' => 'Ancient means very old.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2024,
                'question_text' => 'What is the antonym of "rapid"?',
                'options' => ['slow', 'fast', 'steady', 'quick'],
                'correct_answer' => 0,
                'explanation' => 'Rapid means fast, so the opposite is slow.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2023,
                'question_text' => 'The word "manage" means to:',
                'options' => ['handle', 'destroy', 'ignore', 'delay'],
                'correct_answer' => 0,
                'explanation' => 'Manage means to control or handle something successfully.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Vocabulary',
                'year' => 2022,
                'question_text' => 'What does "seldom" mean?',
                'options' => ['not often', 'always', 'sometimes', 'never'],
                'correct_answer' => 0,
                'explanation' => 'Seldom means rarely or not often.',
                'difficulty' => 'easy',
            ],

            // ── Synonyms and Antonyms ──────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2024,
                'question_text' => 'Choose the synonym of "assist":',
                'options' => ['help', 'fight', 'hide', 'refuse'],
                'correct_answer' => 0,
                'explanation' => 'Assist means help.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2023,
                'question_text' => 'Choose the antonym of "benefit":',
                'options' => ['harm', 'gain', 'profit', 'advantage'],
                'correct_answer' => 0,
                'explanation' => 'The opposite of benefit is harm.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2022,
                'question_text' => 'Choose the synonym of "courage":',
                'options' => ['bravery', 'fear', 'anger', 'silence'],
                'correct_answer' => 0,
                'explanation' => 'Courage means bravery.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2021,
                'question_text' => 'Choose the antonym of "temporary":',
                'options' => ['permanent', 'short', 'brief', 'recent'],
                'correct_answer' => 0,
                'explanation' => 'Temporary means not lasting; permanent is the opposite.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2020,
                'question_text' => 'Choose the synonym of "abundant":',
                'options' => ['plenty', 'tiny', 'scarce', 'empty'],
                'correct_answer' => 0,
                'explanation' => 'Abundant means plentiful.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2019,
                'question_text' => 'Choose the antonym of "ancient":',
                'options' => ['modern', 'old', 'historic', 'aged'],
                'correct_answer' => 0,
                'explanation' => 'Ancient means old; modern is the opposite.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2018,
                'question_text' => 'Choose the synonym of "genuine":',
                'options' => ['real', 'fake', 'weak', 'loud'],
                'correct_answer' => 0,
                'explanation' => 'Genuine means real or authentic.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2024,
                'question_text' => 'Choose the antonym of "victory":',
                'options' => ['defeat', 'success', 'win', 'gain'],
                'correct_answer' => 0,
                'explanation' => 'The opposite of victory is defeat.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2023,
                'question_text' => 'Choose the synonym of "observe":',
                'options' => ['watch', 'ignore', 'speak', 'hide'],
                'correct_answer' => 0,
                'explanation' => 'Observe means watch carefully.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Synonyms and Antonyms',
                'year' => 2022,
                'question_text' => 'Choose the antonym of "increase":',
                'options' => ['decrease', 'raise', 'grow', 'expand'],
                'correct_answer' => 0,
                'explanation' => 'Increase means to become more; decrease is the opposite.',
                'difficulty' => 'easy',
            ],

            // ── Phrasal Verbs ──────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2024,
                'question_text' => 'Give up means to:',
                'options' => ['stop trying', 'start working', 'speak loudly', 'go outside'],
                'correct_answer' => 0,
                'explanation' => 'To give up is to stop trying.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2023,
                'question_text' => 'Look after means to:',
                'options' => ['take care of', 'look away', 'search for', 'turn down'],
                'correct_answer' => 0,
                'explanation' => 'Look after means to care for someone or something.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2022,
                'question_text' => 'Turn down means to:',
                'options' => ['reject', 'increase', 'repair', 'accept'],
                'correct_answer' => 0,
                'explanation' => 'Turn down means refuse or reject.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2021,
                'question_text' => 'Carry on means to:',
                'options' => ['continue', 'sleep', 'argue', 'forget'],
                'correct_answer' => 0,
                'explanation' => 'Carry on means continue.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2020,
                'question_text' => 'Bring up can mean to:',
                'options' => ['mention', 'bury', 'hide', 'push down'],
                'correct_answer' => 0,
                'explanation' => 'Bring up can mean to mention a topic.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2019,
                'question_text' => 'Set off means to:',
                'options' => ['begin a journey', 'put on fire', 'turn back', 'stop suddenly'],
                'correct_answer' => 0,
                'explanation' => 'Set off means to start a journey.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2018,
                'question_text' => 'Come across means to:',
                'options' => ['meet by chance', 'leave quickly', 'shout loudly', 'look carefully'],
                'correct_answer' => 0,
                'explanation' => 'Come across means to find or meet unexpectedly.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2024,
                'question_text' => 'Put off means to:',
                'options' => ['postpone', 'complete', 'destroy', 'welcome'],
                'correct_answer' => 0,
                'explanation' => 'Put off means delay something.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2023,
                'question_text' => 'Run out of means to:',
                'options' => ['have no more', 'run very fast', 'fall over', 'be full of'],
                'correct_answer' => 0,
                'explanation' => 'It means to exhaust a supply.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Phrasal Verbs',
                'year' => 2022,
                'question_text' => 'Look forward to means to:',
                'options' => ['eagerly await', 'look backward', 'avoid completely', 'inspect closely'],
                'correct_answer' => 0,
                'explanation' => 'It means to await something with pleasure.',
                'difficulty' => 'medium',
            ],

            // ── Idioms ─────────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2024,
                'question_text' => 'Bite the bullet means to:',
                'options' => ['endure pain bravely', 'eat quickly', 'speak softly', 'avoid work'],
                'correct_answer' => 0,
                'explanation' => 'The idiom means to face a difficult situation courageously.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2023,
                'question_text' => 'Once in a blue moon means:',
                'options' => ['very rarely', 'every day', 'at night', 'very quickly'],
                'correct_answer' => 0,
                'explanation' => 'The phrase means something that happens rarely.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2022,
                'question_text' => 'Hit the nail on the head means to:',
                'options' => ['be exactly right', 'miss the point', 'be angry', 'work hard'],
                'correct_answer' => 0,
                'explanation' => 'It means to say or do something exactly right.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2021,
                'question_text' => 'Break the ice means to:',
                'options' => ['start a conversation', 'shatter glass', 'get angry', 'leave early'],
                'correct_answer' => 0,
                'explanation' => 'It means to start friendly communication.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2020,
                'question_text' => 'Burn the midnight oil means to:',
                'options' => ['work late into the night', 'cook at midnight', 'sleep early', 'rest outside'],
                'correct_answer' => 0,
                'explanation' => 'The idiom means to study or work late at night.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2019,
                'question_text' => 'A piece of cake means something is:',
                'options' => ['very easy', 'very expensive', 'very dangerous', 'very long'],
                'correct_answer' => 0,
                'explanation' => 'The idiom means something is easy.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2018,
                'question_text' => 'Under the weather means:',
                'options' => ['ill', 'very happy', 'rich', 'confused'],
                'correct_answer' => 0,
                'explanation' => 'It means feeling sick.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2024,
                'question_text' => 'In hot water means to be:',
                'options' => ['in trouble', 'in a warm place', 'very rich', 'very tired'],
                'correct_answer' => 0,
                'explanation' => 'The idiom means to be in difficulty or trouble.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2023,
                'question_text' => 'On cloud nine means to be:',
                'options' => ['very happy', 'very angry', 'sleepy', 'hungry'],
                'correct_answer' => 0,
                'explanation' => 'It means extremely happy.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Idioms',
                'year' => 2022,
                'question_text' => 'The ball is in your court means:',
                'options' => ['it is your turn to act', 'you are playing tennis', 'you are being watched', 'you should leave'],
                'correct_answer' => 0,
                'explanation' => 'It means the next move is yours to make.',
                'difficulty' => 'medium',
            ],

            // ── Oral English ───────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2024,
                'question_text' => 'Which word rhymes with "late"?',
                'options' => ['gate', 'cat', 'cup', 'sit'],
                'correct_answer' => 0,
                'explanation' => 'Late and gate share the same ending sound.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2023,
                'question_text' => 'In the word "computer", the stressed syllable is the:',
                'options' => ['second syllable', 'first syllable', 'third syllable', 'last syllable'],
                'correct_answer' => 0,
                'explanation' => 'Computer is stressed on the second syllable.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2022,
                'question_text' => 'Which word has the same vowel sound as "seat"?',
                'options' => ['tea', 'sit', 'set', 'sat'],
                'correct_answer' => 0,
                'explanation' => 'Seat and tea both have the long /i:/ sound.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2021,
                'question_text' => 'Which word has a silent letter?',
                'options' => ['honest', 'banana', 'table', 'simple'],
                'correct_answer' => 0,
                'explanation' => 'The h in honest is silent.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2020,
                'question_text' => 'The letter combination "sh" represents the sound:',
                'options' => ['/ʃ/', '/z/', '/t/', '/ŋ/'],
                'correct_answer' => 0,
                'explanation' => 'Sh is the voiceless postalveolar fricative sound.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2019,
                'question_text' => 'Which word is stressed on the first syllable?',
                'options' => ['teacher', 'around', 'forget', 'decide'],
                'correct_answer' => 0,
                'explanation' => 'Teacher is stressed on the first syllable.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2018,
                'question_text' => 'Which word rhymes with "through"?',
                'options' => ['blue', 'bread', 'cat', 'form'],
                'correct_answer' => 0,
                'explanation' => 'Through and blue end with the same sound.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2024,
                'question_text' => 'The plural of "knife" is:',
                'options' => ['knives', 'knifes', 'knifees', 'knifs'],
                'correct_answer' => 0,
                'explanation' => 'Knife changes to knives in the plural.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2023,
                'question_text' => 'Which word has two syllables?',
                'options' => ['water', 'school', 'friend', 'small'],
                'correct_answer' => 0,
                'explanation' => 'Water is pronounced with two syllables.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Oral English',
                'year' => 2022,
                'question_text' => 'Choose the word with a long /a:/ sound:',
                'options' => ['car', 'cat', 'cup', 'set'],
                'correct_answer' => 0,
                'explanation' => 'Car contains the long /a:/ sound.',
                'difficulty' => 'easy',
            ],

            // ── Literature and Literary Devices ───────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2024,
                'question_text' => 'A story that teaches a lesson is a:',
                'options' => ['fable', 'novel', 'biography', 'memoir'],
                'correct_answer' => 0,
                'explanation' => 'A fable is a short story that teaches a moral lesson.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2023,
                'question_text' => 'The character who opposes the hero is the:',
                'options' => ['antagonist', 'protagonist', 'narrator', 'spectator'],
                'correct_answer' => 0,
                'explanation' => 'The antagonist is the opposing character or force.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2022,
                'question_text' => 'The turning point in a plot is called the:',
                'options' => ['climax', 'setting', 'preface', 'epilogue'],
                'correct_answer' => 0,
                'explanation' => 'The climax is the most intense or decisive point in the plot.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2021,
                'question_text' => 'A comparison using "like" or "as" is a:',
                'options' => ['simile', 'metaphor', 'hyperbole', 'irony'],
                'correct_answer' => 0,
                'explanation' => 'A simile compares two things using like or as.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2020,
                'question_text' => 'Giving human qualities to non-human things is:',
                'options' => ['personification', 'alliteration', 'pun', 'symbolism'],
                'correct_answer' => 0,
                'explanation' => 'Personification gives human attributes to non-human things.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2019,
                'question_text' => 'A poem with 14 lines is called a:',
                'options' => ['sonnet', 'ballad', 'ode', 'lyric'],
                'correct_answer' => 0,
                'explanation' => 'A sonnet traditionally has 14 lines.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2018,
                'question_text' => 'The time and place of a story is the:',
                'options' => ['setting', 'theme', 'climax', 'mood'],
                'correct_answer' => 0,
                'explanation' => 'Setting refers to the time and place where events happen.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2024,
                'question_text' => 'The central idea of a literary work is the:',
                'options' => ['theme', 'plot', 'setting', 'prologue'],
                'correct_answer' => 0,
                'explanation' => 'Theme is the central idea or message.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2023,
                'question_text' => 'An exaggerated statement is a:',
                'options' => ['hyperbole', 'metaphor', 'simile', 'euphemism'],
                'correct_answer' => 0,
                'explanation' => 'Hyperbole is deliberate exaggeration.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Literature',
                'year' => 2022,
                'question_text' => 'A work that ends sadly with the downfall of the main character is a:',
                'options' => ['tragedy', 'comedy', 'farce', 'satire'],
                'correct_answer' => 0,
                'explanation' => 'A tragedy ends unhappily and often features the fall of the main character.',
                'difficulty' => 'easy',
            ],

            // ── Sentence Structure and Parts of Speech ────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2024,
                'question_text' => 'Identify the gerund in "Swimming is healthy."',
                'options' => ['Swimming', 'healthy', 'is', 'is healthy'],
                'correct_answer' => 0,
                'explanation' => 'Swimming is a verb form acting as a noun.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2023,
                'question_text' => 'Identify the infinitive in "I want to learn."',
                'options' => ['to learn', 'I want', 'learn', 'to'],
                'correct_answer' => 0,
                'explanation' => 'An infinitive is the base form of a verb preceded by to.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2022,
                'question_text' => 'Identify the adverb in "She sings beautifully."',
                'options' => ['beautifully', 'sings', 'She', 'none'],
                'correct_answer' => 0,
                'explanation' => 'Beautifully modifies the verb sings.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2021,
                'question_text' => 'Identify the prepositional phrase in "The book on the table is mine."',
                'options' => ['on the table', 'The book', 'is mine', 'book on'],
                'correct_answer' => 0,
                'explanation' => 'A prepositional phrase begins with a preposition and ends with its object.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2020,
                'question_text' => 'Choose the correct sentence:',
                'options' => ['Neither of the answers is correct.', 'Neither of the answers are correct.', 'Neither of the answer are correct.', 'Neither of the answer is correct.'],
                'correct_answer' => 0,
                'explanation' => 'Neither takes a singular verb when referring to each item separately.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2019,
                'question_text' => 'Which is a simple sentence?',
                'options' => ['We stayed at home.', 'We stayed at home and watched a film.', 'Because it rained, we stayed at home.', 'Although tired, we stayed at home.'],
                'correct_answer' => 0,
                'explanation' => 'A simple sentence has one main clause.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2018,
                'question_text' => 'Which is a compound sentence?',
                'options' => ['I called her, and she replied.', 'Because it rained, we stayed inside.', 'After the match, we went home.', 'Running quickly, he caught the bus.'],
                'correct_answer' => 0,
                'explanation' => 'A compound sentence has two main clauses joined by a conjunction.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2024,
                'question_text' => 'Which is a complex sentence?',
                'options' => ['Because it was raining, we stayed inside.', 'We stayed inside and watched TV.', 'We stayed inside.', 'Stay inside.'],
                'correct_answer' => 0,
                'explanation' => 'A complex sentence has a main clause and a subordinate clause.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2023,
                'question_text' => 'Change to indirect speech: "Please sit down."',
                'options' => ['He asked us to sit down.', 'He said we sit down.', 'He ordered, sit down.', 'He told us sit down.'],
                'correct_answer' => 0,
                'explanation' => 'A polite request in direct speech becomes asked + object + to-infinitive.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Sentence Structure',
                'year' => 2022,
                'question_text' => 'Identify the subject in "The tall boy in the red shirt ran home."',
                'options' => ['boy', 'shirt', 'home', 'ran'],
                'correct_answer' => 0,
                'explanation' => 'The subject is the noun phrase headed by boy.',
                'difficulty' => 'easy',
            ],

            // ── Prepositions and Cloze Usage ──────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2024,
                'question_text' => 'She is good ___ mathematics.',
                'options' => ['at', 'in', 'on', 'with'],
                'correct_answer' => 0,
                'explanation' => 'The correct expression is good at something.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2023,
                'question_text' => 'He depends ___ his parents.',
                'options' => ['on', 'in', 'for', 'with'],
                'correct_answer' => 0,
                'explanation' => 'The verb depend takes the preposition on.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2022,
                'question_text' => 'They arrived ___ time.',
                'options' => ['on', 'in', 'at', 'by'],
                'correct_answer' => 0,
                'explanation' => 'The expression is on time.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2021,
                'question_text' => 'The book belongs ___ me.',
                'options' => ['to', 'for', 'at', 'with'],
                'correct_answer' => 0,
                'explanation' => 'Belong takes the preposition to.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2020,
                'question_text' => 'I have not seen him ___ Monday.',
                'options' => ['since', 'for', 'from', 'during'],
                'correct_answer' => 0,
                'explanation' => 'Since is used with a point in time.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2019,
                'question_text' => 'We walked ___ the bridge.',
                'options' => ['across', 'into', 'under', 'between'],
                'correct_answer' => 0,
                'explanation' => 'Across means from one side to the other.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2018,
                'question_text' => 'She was absent ___ school yesterday.',
                'options' => ['from', 'to', 'at', 'on'],
                'correct_answer' => 0,
                'explanation' => 'Absent from is the standard expression.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2024,
                'question_text' => 'He is superior ___ his colleague.',
                'options' => ['to', 'than', 'with', 'at'],
                'correct_answer' => 0,
                'explanation' => 'Superior takes the preposition to.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2023,
                'question_text' => 'Choose the correct article: She adopted ___ honest boy.',
                'options' => ['an', 'a', 'the', 'no article'],
                'correct_answer' => 0,
                'explanation' => 'Honest begins with a vowel sound, so an is correct.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'English',
                'topic' => 'Prepositions',
                'year' => 2022,
                'question_text' => 'The children ran ___ the road.',
                'options' => ['across', 'between', 'through', 'toward'],
                'correct_answer' => 0,
                'explanation' => 'Across fits the idea of moving from one side to the other.',
                'difficulty' => 'easy',
            ],
        ];

        foreach ($questions as $question) {
            Question::create($this->shuffleOptions($question));
        }
    }

    private function shuffleOptions(array $question): array
    {
        $options = $question['options'];
        $correctText = $options[$question['correct_answer']];

        shuffle($options);

        $question['options'] = $options;
        $question['correct_answer'] = array_search($correctText, $options, true);

        return $question;
    }
}
