<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class MathematicsSeeder extends Seeder
{
    public function run(): void
    {
        Question::truncate();

        $questions = [
            // ── Algebra ─────────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2024,
                'question_text' => 'Solve for x: 2x + 7 = 19.',
                'options' => ['x = 6', 'x = 5', 'x = 4', 'x = 7'],
                'correct_answer' => 0,
                'explanation' => '2x = 19 - 7 = 12, so x = 6.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2023,
                'question_text' => 'If 3(x - 4) = 2x + 5, find x.',
                'options' => ['x = 17', 'x = 13', 'x = 9', 'x = 11'],
                'correct_answer' => 0,
                'explanation' => '3x - 12 = 2x + 5, so x = 17.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2022,
                'question_text' => 'Factorise completely: x^2 - 9.',
                'options' => ['(x - 3)(x + 3)', '(x - 9)(x + 1)', '(x - 1)(x + 9)', '(x + 3)^2'],
                'correct_answer' => 0,
                'explanation' => 'This is a difference of squares: a^2 - b^2 = (a - b)(a + b).',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2021,
                'question_text' => 'Solve x^2 - 5x + 6 = 0.',
                'options' => ['x = 2 or 3', 'x = 1 or 6', 'x = -2 or -3', 'x = 3 or 4'],
                'correct_answer' => 0,
                'explanation' => 'Factorise to (x - 2)(x - 3) = 0.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2020,
                'question_text' => 'Simplify: 4a^2b x 3ab^2.',
                'options' => ['12a^3b^3', '7a^3b^2', '12a^2b^2', '12a^4b^3'],
                'correct_answer' => 0,
                'explanation' => 'Multiply coefficients and add powers of like bases.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2019,
                'question_text' => 'If f(x) = x^2 - 2x, find f(3).',
                'options' => ['3', '6', '9', '1'],
                'correct_answer' => 0,
                'explanation' => 'f(3) = 3^2 - 2(3) = 9 - 6 = 3.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2018,
                'question_text' => 'Solve 5x - 3 = 2x + 12.',
                'options' => ['x = 5', 'x = 3', 'x = 4', 'x = 6'],
                'correct_answer' => 0,
                'explanation' => '3x = 15, so x = 5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2024,
                'question_text' => 'If 2^x = 16, find x.',
                'options' => ['4', '2', '8', '6'],
                'correct_answer' => 0,
                'explanation' => '16 = 2^4.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2023,
                'question_text' => 'Expand (x + 2)(x - 5).',
                'options' => ['x^2 - 3x - 10', 'x^2 + 7x - 10', 'x^2 - 7x + 10', 'x^2 + 3x - 10'],
                'correct_answer' => 0,
                'explanation' => 'Multiply each term: x^2 - 5x + 2x - 10 = x^2 - 3x - 10.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Algebra',
                'year' => 2022,
                'question_text' => 'Simplify: 6x / 3.',
                'options' => ['2x', '3x', 'x/2', '6x'],
                'correct_answer' => 0,
                'explanation' => '6x divided by 3 gives 2x.',
                'difficulty' => 'easy',
            ],

            // ── Indices and Logarithms ─────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2024,
                'question_text' => 'Evaluate 5^0.',
                'options' => ['1', '0', '5', '25'],
                'correct_answer' => 0,
                'explanation' => 'Any non-zero number raised to the power 0 equals 1.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2023,
                'question_text' => 'Simplify 2^3 x 2^4.',
                'options' => ['2^7', '2^12', '2^1', '2^24'],
                'correct_answer' => 0,
                'explanation' => 'Add the indices when the bases are the same: 2^(3+4) = 2^7.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2022,
                'question_text' => 'Simplify (a^3)^2.',
                'options' => ['a^6', 'a^5', 'a^9', 'a^8'],
                'correct_answer' => 0,
                'explanation' => 'Multiply the indices: a^(3 x 2) = a^6.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2021,
                'question_text' => 'Evaluate 10^2 / 10^5.',
                'options' => ['10^-3', '10^3', '10^-7', '10^5'],
                'correct_answer' => 0,
                'explanation' => 'Subtract the indices: 10^(2-5) = 10^-3.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2020,
                'question_text' => 'What is log10 100?',
                'options' => ['2', '1', '10', '3'],
                'correct_answer' => 0,
                'explanation' => '10^2 = 100, so log10 100 = 2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2019,
                'question_text' => 'What is log2 8?',
                'options' => ['3', '2', '4', '1'],
                'correct_answer' => 0,
                'explanation' => '2^3 = 8.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2018,
                'question_text' => 'Evaluate 27^(2/3).',
                'options' => ['9', '6', '3', '18'],
                'correct_answer' => 0,
                'explanation' => '27^(1/3) = 3, and 3^2 = 9.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2024,
                'question_text' => 'Evaluate 16^(3/4).',
                'options' => ['8', '6', '4', '12'],
                'correct_answer' => 0,
                'explanation' => '16^(1/4) = 2, and 2^3 = 8.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2023,
                'question_text' => 'If 4^x = 64, find x.',
                'options' => ['3', '2', '4', '5'],
                'correct_answer' => 0,
                'explanation' => '64 = 4^3.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Indices and Logarithms',
                'year' => 2022,
                'question_text' => 'Evaluate log10 1000.',
                'options' => ['3', '2', '1', '4'],
                'correct_answer' => 0,
                'explanation' => '10^3 = 1000.',
                'difficulty' => 'easy',
            ],

            // ── Geometry ──────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2024,
                'question_text' => 'Find the sum of the interior angles of a triangle.',
                'options' => ['180°', '360°', '90°', '270°'],
                'correct_answer' => 0,
                'explanation' => 'The sum of angles in any triangle is 180 degrees.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2023,
                'question_text' => 'Find the area of a triangle with base 12 cm and height 8 cm.',
                'options' => ['48 cm^2', '96 cm^2', '24 cm^2', '20 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = 1/2 x base x height = 1/2 x 12 x 8 = 48 cm^2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2022,
                'question_text' => 'A circle has radius 7 cm. Find its circumference. Take pi = 22/7.',
                'options' => ['44 cm', '22 cm', '154 cm', '88 cm'],
                'correct_answer' => 0,
                'explanation' => 'Circumference = 2pi r = 2 x 22/7 x 7 = 44 cm.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2021,
                'question_text' => 'In a right-angled triangle, the legs are 6 cm and 8 cm. Find the hypotenuse.',
                'options' => ['10 cm', '12 cm', '14 cm', '8 cm'],
                'correct_answer' => 0,
                'explanation' => 'Use Pythagoras: sqrt(6^2 + 8^2) = sqrt(36 + 64) = 10.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2020,
                'question_text' => 'What is the sum of interior angles of a hexagon?',
                'options' => ['720°', '540°', '360°', '900°'],
                'correct_answer' => 0,
                'explanation' => 'Sum = (n - 2) x 180 = (6 - 2) x 180 = 720 degrees.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2019,
                'question_text' => 'Two parallel lines are cut by a transversal. If one co-interior angle is 65 degrees, find the other.',
                'options' => ['115°', '65°', '125°', '25°'],
                'correct_answer' => 0,
                'explanation' => 'Co-interior angles sum to 180 degrees, so 180 - 65 = 115 degrees.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2018,
                'question_text' => 'Find the area of a sector with radius 6 cm and angle 60 degrees. Take pi = 22/7.',
                'options' => ['18.86 cm^2', '37.71 cm^2', '56.57 cm^2', '12.57 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = (60/360) x (22/7) x 6^2 = 18.86 cm^2 approximately.',
                'difficulty' => 'hard',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2024,
                'question_text' => 'Find the value of each angle in a triangle with angles in the ratio 1:2:3.',
                'options' => ['30°, 60°, 90°', '20°, 40°, 120°', '45°, 45°, 90°', '60°, 60°, 60°'],
                'correct_answer' => 0,
                'explanation' => 'The ratio totals 6 parts. Each part is 30 degrees.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2023,
                'question_text' => 'The angle in a semicircle is:',
                'options' => ['90°', '60°', '45°', '120°'],
                'correct_answer' => 0,
                'explanation' => 'An angle subtended by a diameter is a right angle.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Geometry',
                'year' => 2022,
                'question_text' => 'A rectangle has length 9 cm and width 5 cm. Find its area.',
                'options' => ['45 cm^2', '14 cm^2', '18 cm^2', '90 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = length x width = 9 x 5 = 45 cm^2.',
                'difficulty' => 'easy',
            ],

            // ── Mensuration ────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2024,
                'question_text' => 'Find the volume of a cuboid with dimensions 5 cm, 4 cm and 3 cm.',
                'options' => ['60 cm^3', '12 cm^3', '20 cm^3', '30 cm^3'],
                'correct_answer' => 0,
                'explanation' => 'Volume = l x w x h = 5 x 4 x 3 = 60 cm^3.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2023,
                'question_text' => 'Find the area of a circle with radius 14 cm. Take pi = 22/7.',
                'options' => ['616 cm^2', '308 cm^2', '154 cm^2', '44 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = pi r^2 = 22/7 x 14^2 = 616 cm^2.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2022,
                'question_text' => 'A cylinder has radius 3 cm and height 10 cm. Find its volume. Take pi = 3.14.',
                'options' => ['282.6 cm^3', '94.2 cm^3', '376.8 cm^3', '188.4 cm^3'],
                'correct_answer' => 0,
                'explanation' => 'Volume = pi r^2 h = 3.14 x 9 x 10 = 282.6 cm^3.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2021,
                'question_text' => 'Find the surface area of a cube of side 4 cm.',
                'options' => ['96 cm^2', '64 cm^2', '16 cm^2', '48 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Surface area = 6a^2 = 6 x 4^2 = 96 cm^2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2020,
                'question_text' => 'Find the area of a trapezium with parallel sides 6 cm and 10 cm, and height 5 cm.',
                'options' => ['40 cm^2', '80 cm^2', '30 cm^2', '50 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = 1/2(a + b)h = 1/2(6 + 10) x 5 = 40 cm^2.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2019,
                'question_text' => 'Find the volume of a cone with radius 3 cm and height 12 cm. Take pi = 3.14.',
                'options' => ['113.04 cm^3', '36.00 cm^3', '28.26 cm^3', '226.08 cm^3'],
                'correct_answer' => 0,
                'explanation' => 'Volume = 1/3 pi r^2 h = 1/3 x 3.14 x 9 x 12 = 113.04 cm^3.',
                'difficulty' => 'hard',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2018,
                'question_text' => 'Find the perimeter of a square with side 9 cm.',
                'options' => ['36 cm', '81 cm', '18 cm', '45 cm'],
                'correct_answer' => 0,
                'explanation' => 'Perimeter = 4 x side = 36 cm.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2024,
                'question_text' => 'Find the area of a triangle with base 14 cm and height 5 cm.',
                'options' => ['35 cm^2', '70 cm^2', '19 cm^2', '45 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = 1/2 x 14 x 5 = 35 cm^2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2023,
                'question_text' => 'Find the volume of a sphere of radius 7 cm. Take pi = 22/7.',
                'options' => ['1437.33 cm^3', '616 cm^3', '308 cm^3', '154 cm^3'],
                'correct_answer' => 0,
                'explanation' => 'Volume = 4/3 pi r^3 = 4/3 x 22/7 x 343 = 1437.33 cm^3 approximately.',
                'difficulty' => 'hard',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Mensuration',
                'year' => 2022,
                'question_text' => 'Find the area of a sector of radius 14 cm and angle 90 degrees. Take pi = 22/7.',
                'options' => ['154 cm^2', '308 cm^2', '616 cm^2', '77 cm^2'],
                'correct_answer' => 0,
                'explanation' => 'Area = (90/360) x 22/7 x 14^2 = 154 cm^2.',
                'difficulty' => 'medium',
            ],

            // ── Trigonometry ───────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2024,
                'question_text' => 'If sin theta = 1/2 and theta is acute, find theta.',
                'options' => ['30 degrees', '45 degrees', '60 degrees', '90 degrees'],
                'correct_answer' => 0,
                'explanation' => 'For an acute angle, sin theta = 1/2 at theta = 30 degrees.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2023,
                'question_text' => 'If tan theta = 3/4 and theta is acute, find cos theta.',
                'options' => ['4/5', '3/5', '5/4', '7/5'],
                'correct_answer' => 0,
                'explanation' => 'Use a 3-4-5 right triangle, so cos theta = 4/5.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2022,
                'question_text' => 'Find the value of cos 60 degrees.',
                'options' => ['1/2', '1', '0', 'sqrt(3)/2'],
                'correct_answer' => 0,
                'explanation' => 'cos 60 degrees = 1/2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2021,
                'question_text' => 'A ladder 10 m long leans against a wall. If the foot of the ladder is 6 m from the wall, how high does it reach?',
                'options' => ['8 m', '4 m', '6 m', '12 m'],
                'correct_answer' => 0,
                'explanation' => 'Using Pythagoras, height = sqrt(10^2 - 6^2) = 8 m.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2020,
                'question_text' => 'Find the value of tan 45 degrees.',
                'options' => ['1', '0', 'sqrt(3)', '1/2'],
                'correct_answer' => 0,
                'explanation' => 'tan 45 degrees = 1.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2019,
                'question_text' => 'If cos theta = 1/2 and theta is acute, find theta.',
                'options' => ['60 degrees', '30 degrees', '45 degrees', '90 degrees'],
                'correct_answer' => 0,
                'explanation' => 'cos theta = 1/2 at theta = 60 degrees for an acute angle.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2018,
                'question_text' => 'If opposite = 5, adjacent = 12 and hypotenuse = 13, find sin theta.',
                'options' => ['5/13', '12/13', '13/5', '5/12'],
                'correct_answer' => 0,
                'explanation' => 'sin theta = opposite / hypotenuse = 5/13.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2024,
                'question_text' => 'Find the value of sec 60 degrees.',
                'options' => ['2', '1/2', 'sqrt(3)', '1'],
                'correct_answer' => 0,
                'explanation' => 'sec theta = 1 / cos theta, and cos 60 degrees = 1/2.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2023,
                'question_text' => 'Find the value of cot 45 degrees.',
                'options' => ['1', '0', 'sqrt(3)', '1/2'],
                'correct_answer' => 0,
                'explanation' => 'cot 45 degrees = 1.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Trigonometry',
                'year' => 2022,
                'question_text' => 'If sin theta = sqrt(3)/2 and theta is acute, find theta.',
                'options' => ['60 degrees', '30 degrees', '45 degrees', '90 degrees'],
                'correct_answer' => 0,
                'explanation' => 'sin theta = sqrt(3)/2 at theta = 60 degrees.',
                'difficulty' => 'easy',
            ],

            // ── Coordinate Geometry ───────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2024,
                'question_text' => 'Find the midpoint of the line joining (2, 4) and (6, 8).',
                'options' => ['(4, 6)', '(3, 5)', '(8, 12)', '(2, 6)'],
                'correct_answer' => 0,
                'explanation' => 'Midpoint = ((2 + 6) / 2, (4 + 8) / 2) = (4, 6).',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2023,
                'question_text' => 'Find the gradient of the line through (1, 2) and (3, 6).',
                'options' => ['2', '1/2', '4', '3'],
                'correct_answer' => 0,
                'explanation' => 'Gradient = (6 - 2) / (3 - 1) = 2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2022,
                'question_text' => 'What is the distance between (0, 0) and (3, 4)?',
                'options' => ['5', '7', '4', '3'],
                'correct_answer' => 0,
                'explanation' => 'Distance = sqrt(3^2 + 4^2) = 5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2021,
                'question_text' => 'What is the y-intercept of the line y = 3x + 5?',
                'options' => ['5', '3', '0', '-5'],
                'correct_answer' => 0,
                'explanation' => 'The line crosses the y-axis when x = 0, so y = 5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2020,
                'question_text' => 'What is the gradient of a horizontal line?',
                'options' => ['0', '1', '-1', 'Undefined'],
                'correct_answer' => 0,
                'explanation' => 'A horizontal line has no rise, so its gradient is 0.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2019,
                'question_text' => 'What is the gradient of a line perpendicular to y = x?',
                'options' => ['-1', '1', '0', '2'],
                'correct_answer' => 0,
                'explanation' => 'The gradient of y = x is 1, so the perpendicular gradient is -1.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2018,
                'question_text' => 'Find the midpoint of (-2, 5) and (4, -1).',
                'options' => ['(1, 2)', '(2, 1)', '(0, 4)', '(1, -2)'],
                'correct_answer' => 0,
                'explanation' => 'Midpoint = ((-2 + 4) / 2, (5 + -1) / 2) = (1, 2).',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2024,
                'question_text' => 'Find the equation of the line through the origin and (2, 4).',
                'options' => ['y = 2x', 'y = x + 2', 'y = 4x', 'y = x / 2'],
                'correct_answer' => 0,
                'explanation' => 'Gradient = 4 / 2 = 2, and the line passes through the origin.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2023,
                'question_text' => 'Find the distance between (2, 1) and (2, 7).',
                'options' => ['6', '8', '5', '4'],
                'correct_answer' => 0,
                'explanation' => 'The x-coordinates are equal, so the distance is 7 - 1 = 6.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Coordinate Geometry',
                'year' => 2022,
                'question_text' => 'What is the x-intercept of y = 2x - 4?',
                'options' => ['2', '4', '-2', '0'],
                'correct_answer' => 0,
                'explanation' => 'Set y = 0: 0 = 2x - 4, so x = 2.',
                'difficulty' => 'easy',
            ],

            // ── Statistics ────────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2024,
                'question_text' => 'Find the mean of 2, 4, 6, 8.',
                'options' => ['5', '4', '6', '7'],
                'correct_answer' => 0,
                'explanation' => 'Mean = (2 + 4 + 6 + 8) / 4 = 5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2023,
                'question_text' => 'Find the median of 3, 5, 7, 9, 11.',
                'options' => ['7', '5', '9', '8'],
                'correct_answer' => 0,
                'explanation' => 'The middle value in the ordered list is 7.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2022,
                'question_text' => 'Find the mode of 1, 2, 2, 3, 4.',
                'options' => ['2', '1', '3', '4'],
                'correct_answer' => 0,
                'explanation' => '2 appears most often.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2021,
                'question_text' => 'Find the range of 15, 6, 9, 12.',
                'options' => ['9', '6', '12', '15'],
                'correct_answer' => 0,
                'explanation' => 'Range = 15 - 6 = 9.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2020,
                'question_text' => 'Find the mean of 10, 15, 20, 25.',
                'options' => ['17.5', '15', '20', '18.5'],
                'correct_answer' => 0,
                'explanation' => 'Mean = 70 / 4 = 17.5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2019,
                'question_text' => 'Find the median of 2, 4, 6, 8, 10, 12.',
                'options' => ['7', '6', '8', '7.5'],
                'correct_answer' => 0,
                'explanation' => 'Median = (6 + 8) / 2 = 7.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2018,
                'question_text' => 'Find the mode of 5, 5, 6, 6, 6, 7.',
                'options' => ['6', '5', '7', 'No mode'],
                'correct_answer' => 0,
                'explanation' => '6 appears most often.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2024,
                'question_text' => 'Find the mean of 6, 7, 8, 9, 10.',
                'options' => ['8', '7', '9', '6'],
                'correct_answer' => 0,
                'explanation' => 'Mean = 40 / 5 = 8.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2023,
                'question_text' => 'A data set has values 4, 4, 6, 8, 8, 8, 10. What is the mode?',
                'options' => ['8', '4', '6', '10'],
                'correct_answer' => 0,
                'explanation' => '8 appears most frequently.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Statistics',
                'year' => 2022,
                'question_text' => 'Find the range of 9, 14, 3, 20, 11.',
                'options' => ['17', '11', '20', '14'],
                'correct_answer' => 0,
                'explanation' => 'Range = 20 - 3 = 17.',
                'difficulty' => 'easy',
            ],

            // ── Probability ───────────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2024,
                'question_text' => 'A fair coin is tossed once. What is the probability of getting heads?',
                'options' => ['1/2', '1/3', '1/4', '1'],
                'correct_answer' => 0,
                'explanation' => 'A fair coin has two equally likely outcomes.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2023,
                'question_text' => 'A fair die is thrown once. What is the probability of an even number?',
                'options' => ['1/2', '1/3', '2/3', '1/6'],
                'correct_answer' => 0,
                'explanation' => 'The even outcomes are 2, 4 and 6, so the probability is 3/6 = 1/2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2022,
                'question_text' => 'A bag contains 2 red balls and 3 blue balls. What is the probability of picking a red ball?',
                'options' => ['2/5', '3/5', '1/2', '2/3'],
                'correct_answer' => 0,
                'explanation' => 'Total balls = 5, red balls = 2.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2021,
                'question_text' => 'A standard deck of cards is used. What is the probability of drawing an ace?',
                'options' => ['1/13', '1/4', '4/13', '1/52'],
                'correct_answer' => 0,
                'explanation' => 'There are 4 aces in 52 cards, so probability = 4/52 = 1/13.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2020,
                'question_text' => 'Two coins are tossed. What is the probability of exactly one head?',
                'options' => ['1/2', '1/4', '3/4', '1'],
                'correct_answer' => 0,
                'explanation' => 'Possible outcomes are HH, HT, TH, TT. Exactly one head occurs in 2 of 4 cases.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2019,
                'question_text' => 'A die is thrown. What is the probability of getting a number greater than 4?',
                'options' => ['1/3', '1/2', '2/3', '1/6'],
                'correct_answer' => 0,
                'explanation' => 'The numbers greater than 4 are 5 and 6, so probability = 2/6 = 1/3.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2018,
                'question_text' => 'A bag contains 5 green balls and 7 yellow balls. What is the probability of picking a yellow ball?',
                'options' => ['7/12', '5/12', '1/2', '7/5'],
                'correct_answer' => 0,
                'explanation' => 'Total balls = 12, yellow balls = 7.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2024,
                'question_text' => 'What is the probability of selecting a vowel from the letters A, B, C, D, E?',
                'options' => ['2/5', '1/5', '3/5', '4/5'],
                'correct_answer' => 0,
                'explanation' => 'The vowels are A and E, so probability = 2/5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2023,
                'question_text' => 'What is the probability of an impossible event?',
                'options' => ['0', '1', '1/2', 'Undefined'],
                'correct_answer' => 0,
                'explanation' => 'An impossible event cannot occur, so its probability is 0.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Probability',
                'year' => 2022,
                'question_text' => 'What is the probability of a certain event?',
                'options' => ['1', '0', '1/2', '2'],
                'correct_answer' => 0,
                'explanation' => 'A certain event always occurs, so its probability is 1.',
                'difficulty' => 'easy',
            ],

            // ── Sequences and Series ──────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2024,
                'question_text' => 'Find the next term in the arithmetic progression 2, 5, 8, 11, ...',
                'options' => ['14', '13', '15', '16'],
                'correct_answer' => 0,
                'explanation' => 'The common difference is 3, so the next term is 14.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2023,
                'question_text' => 'Find the 3rd term of the sequence 4, 8, 12, 16, ...',
                'options' => ['12', '8', '16', '20'],
                'correct_answer' => 0,
                'explanation' => 'The 3rd term is 12.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2022,
                'question_text' => 'Find the next term in the geometric sequence 2, 6, 18, ...',
                'options' => ['54', '36', '48', '72'],
                'correct_answer' => 0,
                'explanation' => 'Each term is multiplied by 3, so the next term is 54.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2021,
                'question_text' => 'Find the 10th term of the arithmetic sequence 5, 9, 13, ...',
                'options' => ['41', '45', '37', '39'],
                'correct_answer' => 0,
                'explanation' => 'a_n = 5 + 9(4) = 41.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2020,
                'question_text' => 'What is the common difference in 7, 10, 13, 16, ...?',
                'options' => ['3', '2', '4', '5'],
                'correct_answer' => 0,
                'explanation' => 'Each term increases by 3.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2019,
                'question_text' => 'Find the 5th term of the sequence 1, 3, 5, 7, ...',
                'options' => ['9', '11', '10', '8'],
                'correct_answer' => 0,
                'explanation' => 'The odd-number sequence gives 9 as the 5th term.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2018,
                'question_text' => 'If the first term of a geometric progression is 2 and the common ratio is 3, what is the 4th term?',
                'options' => ['54', '36', '27', '18'],
                'correct_answer' => 0,
                'explanation' => 'Terms are 2, 6, 18, 54.',
                'difficulty' => 'medium',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2024,
                'question_text' => 'Find the next term in 100, 90, 80, 70, ...',
                'options' => ['60', '65', '55', '50'],
                'correct_answer' => 0,
                'explanation' => 'The common difference is -10.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2023,
                'question_text' => 'Find the sum of the first three odd numbers.',
                'options' => ['9', '6', '12', '15'],
                'correct_answer' => 0,
                'explanation' => '1 + 3 + 5 = 9.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sequences and Series',
                'year' => 2022,
                'question_text' => 'What is the nth term of the sequence 5, 9, 13, 17, ...?',
                'options' => ['4n + 1', '4n - 1', '5n + 4', '3n + 2'],
                'correct_answer' => 0,
                'explanation' => 'The sequence has first term 5 and common difference 4, so a_n = 5 + 4(n - 1) = 4n + 1.',
                'difficulty' => 'medium',
            ],

            // ── Sets and Functions ────────────────────────────────────────
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2024,
                'question_text' => 'If A = {1, 2, 3} and B = {3, 4, 5}, what is A intersect B?',
                'options' => ['{3}', '{1, 2}', '{4, 5}', '{1, 2, 3, 4, 5}'],
                'correct_answer' => 0,
                'explanation' => 'The common element is 3.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2023,
                'question_text' => 'If A = {1, 2, 3} and B = {3, 4, 5}, what is A union B?',
                'options' => ['{1, 2, 3, 4, 5}', '{3}', '{1, 2}', '{4, 5}'],
                'correct_answer' => 0,
                'explanation' => 'Union contains all distinct elements from both sets.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2022,
                'question_text' => 'If the universal set has 10 elements and set A has 4 elements, how many elements are in A complement?',
                'options' => ['6', '4', '10', '14'],
                'correct_answer' => 0,
                'explanation' => 'A complement contains the elements not in A, so 10 - 4 = 6.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2021,
                'question_text' => 'If f(x) = 2x + 1, find f(4).',
                'options' => ['9', '8', '7', '6'],
                'correct_answer' => 0,
                'explanation' => 'f(4) = 2(4) + 1 = 9.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2020,
                'question_text' => 'If f(x) = x^2, find f(-3).',
                'options' => ['9', '-9', '6', '3'],
                'correct_answer' => 0,
                'explanation' => 'f(-3) = (-3)^2 = 9.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2019,
                'question_text' => 'What is the inverse of f(x) = x + 5?',
                'options' => ['x - 5', 'x + 5', '5x', '1 / x'],
                'correct_answer' => 0,
                'explanation' => 'To reverse x + 5, subtract 5.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2018,
                'question_text' => 'If x^2 = 49, what are the values of x?',
                'options' => ['7 or -7', '7 only', '-7 only', '49 or -49'],
                'correct_answer' => 0,
                'explanation' => 'Both 7 and -7 square to give 49.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2024,
                'question_text' => 'If A is a subset of B and B is a subset of C, then A is a subset of:',
                'options' => ['C', 'A', 'B', 'A and B'],
                'correct_answer' => 0,
                'explanation' => 'Subset relation is transitive.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'JAMB',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2022,
                'question_text' => 'If A = {2, 4, 6, 8} and B = {4, 8, 12}, what is A intersect B?',
                'options' => ['{4, 8}', '{2, 6}', '{12}', '{2, 4, 6, 8, 12}'],
                'correct_answer' => 0,
                'explanation' => 'The common elements are 4 and 8.',
                'difficulty' => 'easy',
            ],
            [
                'exam_board' => 'WAEC',
                'subject' => 'Mathematics',
                'topic' => 'Sets and Functions',
                'year' => 2021,
                'question_text' => 'If f(x) = x - 3, what is f(10)?',
                'options' => ['7', '13', '3', '10'],
                'correct_answer' => 0,
                'explanation' => 'f(10) = 10 - 3 = 7.',
                'difficulty' => 'easy',
            ],
        ];

        foreach ($questions as $question) {
            Question::create($this->shuffleOptions($question));
        }
    }

    private function shuffleOptions(array $question): array
    {
        $options = $question['options'];
        $correctText = $options[$question['correct_answer']];

        shuffle($options);

        $question['options'] = $options;
        $question['correct_answer'] = array_search($correctText, $options, true);

        return $question;
    }
}
